QuaternionICP: ICP Namespace Reference
ICP Namespace Reference
Namespaces
namespace Defaults
Default parameter presets for common ICP configurations.
namespace RandomSeeds
Deterministic seeds for reproducible random perturbations.
Classes
struct BidirectionalCorrs
Bidirectional correspondences for ICP.
struct CeresICPResult
Result from full Ceres ICP solve.
struct CeresInnerSolveResult
Result from inner solver (after Ceres optimization)
struct CeresTwoPoseInnerResult
Result from two-pose inner solver.
struct CeresTwoPoseResult
Result from full two-pose ICP solve.
struct Edge
class EmbreeBackend
class ForwardRayLeft< RayJacobianSimplified >
Forward left-perturbation Jacobian for ray-projected point-to-plane ICP.
struct GeometryWeighting
Geometry weighting parameters for incidence-based weighting.
class GridSearchBackend
struct ICPResult
Result from full ICP solve.
struct InnerParams
Inner loop parameters for solver iterations.
struct InnerSolveResult
Result from the inner solver after iterating to convergence.
class IntersectionBackend
struct LineSearchParams
Line search parameters for step size selection.
struct LMParams
Levenberg-Marquardt damping parameters.
struct MultiViewICPResult
struct OuterParams
Outer loop parameters for correspondence updates.
struct PerturbationRNGs
Container for random number generators used in pose perturbation.
struct RayHit
class ReverseRayLeft< RayJacobianSimplified >
Reverse left-perturbation Jacobian for ray-projected point-to-plane ICP.
class SE3ScaledManifold
Custom Ceres manifold for SE(3) with rotation scaling.
struct SessionParams
Session-level parameters.
Typedefs
using Pose7 = Eigen::Matrix< double, 7, 1 >
SE(3) pose as 7D vector: [qx, qy, qz, qw, tx, ty, tz].
using SophusSE3Manifold = Sophus::Manifold< Sophus::SE3 >
Sophus SE3 manifold for Ceres (used by two-pose solver)
using Tangent6 = Vector6
[Vso3]
Vector Types
using Vector2 = Eigen::Vector2d
2D vector (double)
using Vector3 = Eigen::Vector3d
3D vector (double)
using Vector4 = Eigen::Vector4d
4D vector (double)
using VectorX = Eigen::VectorXd
Dynamic-size vector (double)
using Vector6 = Eigen::Matrix< double, 6, 1 >
6D vector (tangent space)
Matrix Types
using Matrix2 = Eigen::Matrix2d
2x2 matrix (double)
using Matrix3 = Eigen::Matrix3d
3x3 matrix (double)
using Matrix4 = Eigen::Matrix4d
4x4 matrix (double)
using MatrixX = Eigen::MatrixXd
Dynamic-size matrix (double)
using Matrix6 = Eigen::Matrix< double, 6, 6 >
6x6 matrix
using Matrix3x4 = Eigen::Matrix< double, 3, 4 >
3x4 matrix
using Matrix4x3 = Eigen::Matrix< double, 4, 3 >
4x3 matrix
using Matrix7x6 = Eigen::Matrix< double, 7, 6 >
7x6 matrix (Plus Jacobian)
Geometry Types
using Quaternion = Eigen::Quaterniond
Unit quaternion (double)
using AngleAxis = Eigen::AngleAxisd
Axis-angle rotation (double)
Enumerations
enum class SolverBackend { HandRolled , Ceres }
Solver backend selection.
enum class SolverType { GaussNewton , LevenbergMarquardt }
Inner solver type selection.
enum class JacobianPolicy { Simplified , Consistent }
Jacobian computation policy for ray-projection residuals.
enum class LMStrategy { Simple , GainRatio }
Lambda update strategy for Levenberg-Marquardt.
enum class LinearSolverType {
DenseQR , DenseSchur , SparseSchur , IterativeSchur ,
CudaDenseCholesky , CudaSparseCholesky
}
Linear solver type for Ceres backend.
enum class PreconditionerType { Identity , Jacobi , SchurJacobi }
Preconditioner type for iterative solvers.
enum class WeightingMode { Abs , SqrtAbs }
Incidence weighting mode for grazing angle handling.
enum class IntersectionBackendType { Auto , GridSearch , Embree }
Functions
void setDefaultIntersectionBackend (IntersectionBackendType type)
IntersectionBackendType getDefaultIntersectionBackend ()
bool isBackendAvailable (IntersectionBackendType type)
std::unique_ptr< IntersectionBackend > createIntersectionBackend (IntersectionBackendType type)
bool hasSuiteSparseSupport ()
Check if Ceres was built with SuiteSparse support.
bool hasCudaSupport ()
Check if Ceres was built with CUDA support.
bool isLinearSolverAvailable (const std::string &solverName)
Check if a linear solver type is available.
std::string getLinearSolverUnavailableReason (const std::string &solverName)
Get a description of why a solver is unavailable.
void printCeresCapabilities ()
Print available Ceres features to stdout.
std::vector< int > parseGridIndices (const std::string &str)
InnerParams commonOptionsToInnerParams (const CommonOptions &opts)
OuterParams commonOptionsToOuterParams (const CommonOptions &opts)
SessionParams commonOptionsToSessionParams (const CommonOptions &opts)
void printCommonConfig (const CommonOptions &opts)
std::vector< Correspondence > computeRayCorrespondences (const Grid &srcGrid, const Grid &tgtGrid, const Eigen::Vector3f &rayDir, const Eigen::Isometry3d &srcToTgt, float maxDist, int subsampleX=1, int subsampleY=1)
BidirectionalCorrs computeBidirectionalCorrs (const Grid &source, const Grid &target, const Eigen::Vector3f &rayDir, const Eigen::Isometry3d &srcToTgt, float maxDist, int subsampleX=1, int subsampleY=1)
Quaternion randomQuaternion (std::mt19937 &rng)
Generate a random unit quaternion.
template<int N>
Eigen::Matrix< double, N, 1 > randomUnitVector (std::mt19937 &rng)
Generate a random unit vector in R^N.
Vector3 randomVector3 (std::mt19937 &rng, double scale=1.0)
Generate a random 3D vector with uniform distribution.
Pose7 identityPose ()
Create identity pose.
Pose7 isometryToPose7 (const Eigen::Isometry3d &iso)
Convert Isometry3d to Pose7.
Eigen::Isometry3d pose7ToIsometry (const Pose7 &pose)
Convert Pose7 to Isometry3d.
Pose7 translationPose (double tx, double ty, double tz)
Create pose from translation only (identity rotation).
Pose7 rotationPose (const Vector3 &axisAngle)
Create pose from axis-angle rotation (no translation).
Eigen::Quaterniond perturbRotation (const Eigen::Quaterniond &q, double stddevDeg, std::mt19937 &gen)
Add random rotation noise to a quaternion.
void perturbPoseRotation (Pose7 &pose, double stddevDeg, std::mt19937 &gen)
Perturb the rotation component of a Pose7 in-place.
void perturbPoseTranslation (Pose7 &pose, double stddev, std::mt19937 &gen)
Perturb the translation component of a Pose7 in-place.
Grid createHeightfieldGrid (int nx, int ny, float dx, float dy, float amp, float freq)
Grid createTwoHemispheresGrid (int nx, int ny, float dx, float dy, float radius, float separation)
template<typename JacobianPolicy = RayJacobianSimplified>
CeresInnerSolveResult solveInnerCeres (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &innerParams=InnerParams())
template<typename JacobianPolicy = RayJacobianSimplified>
CeresICPResult solveICPCeres (const Grid &source, const Grid &target, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &innerParams=InnerParams(), const OuterParams &outerParams=OuterParams())
template<typename JacobianPolicy = RayJacobianSimplified>
CeresTwoPoseInnerResult solveInnerCeresTwoPose (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPoseA, const Pose7 &initialPoseB, const Vector3 &rayDirA, const Vector3 &rayDirB, const GeometryWeighting &weighting, const ceres::Solver::Options &ceresOptions, bool fixPoseA=false)
Pose7 computeRelativePose (const Pose7 &poseA, const Pose7 &poseB)
template<typename JacobianPolicy = RayJacobianSimplified>
CeresTwoPoseResult solveICPCeresTwoPose (const Grid &gridA, const Grid &gridB, const Pose7 &initialPoseA, const Pose7 &initialPoseB, const Vector3 &rayDir, const GeometryWeighting &weighting, const InnerParams &innerParams, const OuterParams &outerParams, bool fixPoseA=false)
template<typename JacobianPolicy = RayJacobianSimplified>
double computeCostAtPose (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &pose, const Vector3 &rayDir, const GeometryWeighting &weighting)
Compute cost at a given pose.
bool isDeltaConverged (const Tangent6 &delta, double transThreshold, double rotThreshold)
Check if delta is below convergence thresholds.
void applyDeltaAndNormalize (Pose7 &pose, const Tangent6 &delta, double rotationScale=1.0)
Apply SE(3) update and normalize quaternion.
template<typename JacobianPolicy = RayJacobianSimplified>
double lineSearch (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &pose, const Tangent6 &delta, double currentCost, const Vector3 &rayDir, const GeometryWeighting &weighting, const LineSearchParams &params, double rotationScale=1.0)
Backtracking line search to find optimal step size.
template<typename JacobianPolicy = RayJacobianSimplified>
double buildNormalEquations (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &pose, const Vector3 &rayDir, const GeometryWeighting &weighting, Matrix6 &H, Vector6 &b, int &fwd_valid, int &rev_valid, double rotationScale=1.0)
Build normal equations and compute cost in one pass.
double computeModelCostChange (const Tangent6 &delta, const Vector6 &b)
double nielsenRadiusFactor (double rho)
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInnerLMGainRatio (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInnerLMSimple (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInnerLM (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
ceres::Solver::Options toCeresSolverOptions (const InnerParams &inner)
Convert InnerParams to Ceres solver options.
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInnerGN (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInner (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
template<typename JacobianPolicy = RayJacobianSimplified>
ICPResult solveICP (const Grid &source, const Grid &target, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &innerParams=InnerParams(), const OuterParams &outerParams=OuterParams())
Pose7 se3PlusLeft (const Pose7 &x, const Tangent6 &delta)
SE(3) Plus operation using left-multiplication (space-frame perturbation).
void applyDeltaLeftAndNormalize (Pose7 &pose, const Tangent6 &delta)
Apply left SE(3) update and normalize quaternion.
template<typename JacobianPolicy = RayJacobianSimplified>
double buildNormalEquationsLeft (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &pose, const Vector3 &rayDirSource, const GeometryWeighting &weighting, Matrix6 &H, Vector6 &b, int &fwd_valid, int &rev_valid)
Build normal equations using left-perturbation Jacobians.
template<typename JacobianPolicy = RayJacobianSimplified>
double computeCostAtPoseLeft (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &pose, const Vector3 &rayDirSource, const GeometryWeighting &weighting)
Compute cost at a given pose using left-perturbation residuals.
template<typename JacobianPolicy = RayJacobianSimplified>
InnerSolveResult solveInnerGNLeft (const std::vector< Correspondence > &fwdCorrs, const std::vector< Correspondence > &revCorrs, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &params=InnerParams())
Gauss-Newton inner solver using left-perturbation.
template<typename JacobianPolicy = RayJacobianSimplified>
ICPResult solveICPLeft (const Grid &source, const Grid &target, const Pose7 &initialPose, const Vector3 &rayDir, const GeometryWeighting &weighting=GeometryWeighting(), const InnerParams &innerParams=InnerParams(), const OuterParams &outerParams=OuterParams())
Full ICP solver using left-perturbation.
double computeForwardJacobian (const Eigen::Vector3f &srcPoint, const Eigen::Vector3f &tgtPoint, const Eigen::Vector3f &tgtNormal, const Eigen::Matrix3d &R, const Eigen::Vector3d &t, const Eigen::Vector3f &rayDir, Eigen::Matrix< double, 1, 6 > &J, const GeometryWeighting &weighting=GeometryWeighting())
Compute forward left-perturbation Jacobian (simplified).
double computeReverseJacobian (const Eigen::Vector3f &srcPoint, const Eigen::Vector3f &tgtPoint, const Eigen::Vector3f &tgtNormal, const Eigen::Matrix3d &R, const Eigen::Vector3d &t, const Eigen::Vector3f &rayDir, Eigen::Matrix< double, 1, 6 > &J, const GeometryWeighting &weighting=GeometryWeighting())
Compute reverse left-perturbation Jacobian (simplified).
std::vector< Edge > buildEdges (const std::vector< Grid > &grids, const std::vector< Pose7 > &poses, const OuterParams &outer, bool verbose)
MultiViewICPResult runMultiViewICP (std::vector< Grid > &grids, const SessionParams &session, const OuterParams &outer, const InnerParams &inner)
std::vector< std::vector< int > > buildCorrespondenceMatrix (const std::vector< Edge > &edges, size_t numGrids)
void printConnectivityMatrix (const std::vector< std::vector< int > > &counts)
void printResultsTable (const std::vector< Pose7 > &finalPoses, const std::vector< Pose7 > &initialPoses, const std::vector< Pose7 > &groundTruth)
Matrix3 skew (const Vector3 &w)
Compute the skew-symmetric matrix from a 3D vector.
Quaternion quatExpSO3 (const Vector3 &w)
SO(3) exponential map in quaternion form.
Matrix3 Vso3 (const Vector3 &w)
Left Jacobian of SO(3).
Pose7 se3Plus (const Pose7 &x, const Tangent6 &delta)
SE(3) Plus operation using right-multiplication (body-frame perturbation).
Matrix7x6 plusJacobian7x6 (const Pose7 &x)
SE(3) chart Jacobian P(x) for the right-multiplicative Plus operation.
Pose7 se3PlusScaled (const Pose7 &x, const Tangent6 &delta, double rotationScale)
SE(3) Plus operation with rotation scaling for conditioning.
Matrix7x6 plusJacobian7x6Scaled (const Pose7 &x, double rotationScale)
SE(3) chart Jacobian with rotation scaling for conditioning.
Eigen::Matrix< double, 1, 6 > jacobian7Dto6D (const double *J7, const double *x)
Project 7D ambient Jacobian to 6D local (tangent space) Jacobian.
std::array< Matrix3, 4 > dR_dq_mats (const Quaternion &q)
Derivatives of rotation matrix R w.r.t. quaternion components.
Matrix3x4 dRv_dq (const Quaternion &q, const Vector3 &v)
Derivative of R(q) * v w.r.t. quaternion q.
Matrix3x4 dRTv_dq (const Quaternion &q, const Vector3 &v)
Derivative of R(q)^T * v w.r.t. quaternion q.
std::string poseToString (const Pose7 &pose)
Format a Pose7 as a human-readable string.
std::pair< Grid, Grid > createTestGrids (const CommonOptions &opts, bool verbose=false)
Variables
constexpr double kSmallAngleThreshold = 1e-12
Small angle threshold for Taylor expansion in SO(3)/SE(3) operations.
Detailed Description
Ceres-based two-pose ICP solver.
Optimizes two poses simultaneously using bidirectional correspondences. Uses ForwardRayCostTwoPose and ReverseRayCostTwoPose as Ceres cost functions with <1, 7, 7> dimensions.
Levenberg-Marquardt solvers for ICP.
Provides two LM strategies:
Simple: Binary accept/reject with fixed lambda multipliers
GainRatio: Ceres-style gain ratio with Nielsen radius update
See also
ICPSolver.h for Gauss-Newton solver and outer loop
Ambient (7D) Jacobians for ray-projection ICP.
Ceres 2.2-compatible cost functions using 7D ambient parameterization. Policy-based design via template specialization.
Residual: r = a/b where a = n^T (x_transformed - q_surface) b = n^T d (ray direction dot normal)
Two-pose ambient (7D) Jacobians for ray-projection ICP.
Ceres cost functions with <1, 7, 7> dimensions for optimizing two poses. Policy-based design via template specialization.
Forward: ray from frame A hits surface in frame B Reverse: ray from frame B hits surface in frame A
Residual: r = a/b where a = n^T (x_transformed - q_surface) b = n^T d (ray direction dot normal)
Left-perturbation (tangent/6D) Jacobians for ray-projection ICP.
Left-perturbation Jacobians using se(3) tangent space parameterization. Policy-based design via template specialization (matching JacobiansAmbient.h).
Residual: r = a/b where a = n^T (x_transformed - q_surface) b = n^T d (ray direction dot normal)
These Jacobians use LEFT perturbation (space/fixed frame): T_new = exp(delta_xi_hat) * T
Compare to JacobiansAmbient.h which uses RIGHT perturbation (body/moving frame): T_new = T * exp(delta_xi_hat)
The relationship between them is: J_left = J_right * Ad_T^{-1}
Multi-view ICP for N grids.
Edge-based approach:
Use AABB overlap to find candidate grid pairs
Compute bidirectional correspondences for overlapping pairs
Build Ceres problem with all edges using ForwardRayCostTwoPose/ReverseRayCostTwoPose
Utilities for creating and managing test grids.
Typedef Documentation
Tangent6
using ICP::Tangent6 = typedef Vector6
[Vso3]
SE(3) tangent vector: [v_x, v_y, v_z, w_x, w_y, w_z]
Definition at line 272 of file SE3.h.
Enumeration Type Documentation
IntersectionBackendType
enum class ICP::IntersectionBackendType strong
Available intersection backend types.
Enumerator
Auto
Use default (GridSearch if available, else Embree)
GridSearch
GridSearch linear projection (fast for structured grids)
Embree
Intel Embree BVH (general meshes)
Definition at line 23 of file IntersectionBackend.h.
JacobianPolicy
enum class ICP::JacobianPolicy strong
Jacobian computation policy for ray-projection residuals.
Controls whether the Jacobian includes the derivative of the denominator in the ray-plane intersection formula.
Enumerator
Simplified
Ignore db/dq term (faster, approximate but often sufficient)
Consistent
Full quotient rule including db/dq (mathematically exact)
Definition at line 74 of file ICPParams.h.
LinearSolverType
enum class ICP::LinearSolverType strong
Linear solver type for Ceres backend.
Selects the algorithm used to solve the linear system at each iteration. The optimal choice depends on problem size and available hardware.
Enumerator
DenseQR
Dense QR decomposition (default, good for small problems)
DenseSchur
Dense Schur complement (for bundle adjustment style problems)
SparseSchur
Sparse Schur complement (for larger sparse problems)
IterativeSchur
Iterative Schur (good for large multi-view problems)
CudaDenseCholesky
GPU-accelerated dense Cholesky (requires CUDA build)
CudaSparseCholesky
GPU-accelerated sparse Cholesky (requires CUDA + SuiteSparse)
Definition at line 97 of file ICPParams.h.
LMStrategy
enum class ICP::LMStrategy strong
Lambda update strategy for Levenberg-Marquardt.
Determines how the damping parameter lambda is adjusted during optimization.
Enumerator
Simple
Binary accept/reject with fixed multipliers (lambdaUp/lambdaDown)
GainRatio
Ceres-style gain ratio with Nielsen update rule.
Definition at line 85 of file ICPParams.h.
PreconditionerType
enum class ICP::PreconditionerType strong
Preconditioner type for iterative solvers.
Used with IterativeSchur linear solver to improve convergence.
Enumerator
Identity
No preconditioning.
Jacobi
Jacobi (diagonal) preconditioner.
SchurJacobi
Block Jacobi on the Schur complement.
Definition at line 112 of file ICPParams.h.
SolverBackend
enum class ICP::SolverBackend strong
Solver backend selection.
Determines which optimization backend is used for the ICP inner loop.
Enumerator
HandRolled
Hand-rolled implementation (Gauss-Newton or Levenberg-Marquardt)
Ceres
Ceres Solver-based implementation with automatic differentiation.
Definition at line 50 of file ICPParams.h.
SolverType
enum class ICP::SolverType strong
Inner solver type selection.
Selects between Gauss-Newton (no damping) and Levenberg-Marquardt (adaptive damping) for the nonlinear least-squares optimization.
Enumerator
GaussNewton
Gauss-Newton solver (faster but may diverge)
LevenbergMarquardt
Levenberg-Marquardt solver (more robust with damping)
Definition at line 62 of file ICPParams.h.
WeightingMode
enum class ICP::WeightingMode strong
Incidence weighting mode for grazing angle handling.
Controls how the cosine of the incidence angle affects correspondence weights. Larger weights for perpendicular incidence reduce sensitivity to grazing angles.
Enumerator
Abs
Linear weighting: weight = |cos(angle)|.
SqrtAbs
Square root weighting: weight = sqrt(|cos(angle)|)
Definition at line 125 of file ICPParams.h.
Function Documentation
applyDeltaAndNormalize()
void ICP::applyDeltaAndNormalize (Pose7 & pose, const Tangent6 & delta, double rotationScale = 1.0) inline
Apply SE(3) update and normalize quaternion.
Updates the pose using right-multiplication: T_new = T * Exp(delta). The quaternion component is normalized after the update.
Parameters
[in,out] pose Current pose, modified in place
delta Tangent space update [v_x, v_y, v_z, w_x, w_y, w_z]
rotationScale Characteristic length for rotation scaling (1.0 = no scaling)
Definition at line 138 of file ICPHelpers.h.
References se3Plus(), and se3PlusScaled().
Referenced by lineSearch(), solveInnerGN(), solveInnerLMGainRatio(), and solveInnerLMSimple().
buildCorrespondenceMatrix()
std::vector< std::vector< int > > ICP::buildCorrespondenceMatrix (const std::vector< Edge > & edges, size_t numGrids)
Build correspondence count matrix from edges.
Parameters
edges Vector of edges with correspondences
numGrids Number of grids
Returns
NxN matrix where [i][j] = count of correspondences from i to j
Definition at line 355 of file MultiViewICP.cpp.
Referenced by runMultiViewICP().
buildEdges()
std::vector< Edge > ICP::buildEdges (const std::vector< Grid > & grids, const std::vector< Pose7 > & poses, const OuterParams & outer, bool verbose = false)
Build edges between overlapping grid pairs using current poses.
For each pair (i, j) where i < j:
Check AABB overlap (using current poses)
Compute forward correspondences (i j)
Compute reverse correspondences (j i)
Add edges that meet minMatch threshold
Parameters
grids Vector of grids
poses Current Pose7 for each grid
outer Outer loop parameters (rayDir, maxDist, subsampling, etc.)
verbose Print edge info
Returns
Vector of edges
Definition at line 21 of file MultiViewICP.cpp.
References ICP::OuterParams::maxCorrespondences, ICP::OuterParams::maxDist, ICP::OuterParams::maxNeighbors, ICP::OuterParams::minMatch, pose7ToIsometry(), and ICP::OuterParams::rayDir.
Referenced by runMultiViewICP().
buildNormalEquations()
template<typename JacobianPolicy = RayJacobianSimplified> double ICP::buildNormalEquations (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & pose, const Vector3 & rayDir, const GeometryWeighting & weighting, Matrix6 & H, Vector6 & b, int & fwd_valid, int & rev_valid, double rotationScale = 1.0)
Build normal equations and compute cost in one pass.
Accumulates the Gauss-Newton normal equations by iterating over all correspondences. Computes the Hessian approximation H = J^T J, gradient b = J^T r, and sum of squared residuals in a single pass.
The Jacobians are computed in the 7D ambient space and projected to 6D tangent space using the plus-Jacobian.
Template Parameters
JacobianPolicy Jacobian computation policy (simplified or consistent)
Parameters
fwdCorrs Forward correspondences (source to target)
revCorrs Reverse correspondences (target to source)
pose Current pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction for projection
weighting Geometry weighting parameters
[out] H Hessian approximation (6x6 matrix J^T J)
[out] b Gradient vector (6x1 vector J^T r)
[out] fwd_valid Number of valid forward correspondences used
[out] rev_valid Number of valid reverse correspondences used
rotationScale Characteristic length for rotation scaling (1.0 = no scaling)
Returns
Sum of squared residuals (cost)
Definition at line 231 of file ICPHelpers.h.
References plusJacobian7x6(), and plusJacobian7x6Scaled().
buildNormalEquationsLeft()
template<typename JacobianPolicy = RayJacobianSimplified> double ICP::buildNormalEquationsLeft (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & pose, const Vector3 & rayDirSource, const GeometryWeighting & weighting, Matrix6 & H, Vector6 & b, int & fwd_valid, int & rev_valid)
Build normal equations using left-perturbation Jacobians.
Uses ForwardRayLeft and ReverseRayLeft which compute Jacobians directly in 6D tangent space (no projection needed).
Template Parameters
JacobianPolicy Jacobian computation policy (simplified or consistent)
Parameters
fwdCorrs Forward correspondences (source to target)
revCorrs Reverse correspondences (target to source)
pose Current pose [qx, qy, qz, qw, tx, ty, tz]
rayDirSource Ray direction in source frame (for forward: transformed to target)
weighting Geometry weighting parameters
[out] H Hessian approximation (6x6 matrix J^T J)
[out] b Gradient vector (6x1 vector J^T r)
[out] fwd_valid Number of valid forward correspondences used
[out] rev_valid Number of valid reverse correspondences used
Returns
Sum of squared residuals (cost)
Definition at line 114 of file ICPSolverLeft.h.
commonOptionsToInnerParams()
InnerParams ICP::commonOptionsToInnerParams (const CommonOptions & opts)
Convert CommonOptions to InnerParams.
Definition at line 372 of file CommonOptions.cpp.
References ICP::LineSearchParams::alpha, ICP::LineSearchParams::beta, CudaDenseCholesky, CudaSparseCholesky, ICP::InnerParams::damping, DenseQR, DenseSchur, ICP::LineSearchParams::enabled, ICP::LMParams::fixedLambda, GaussNewton, Identity, IterativeSchur, Jacobi, ICP::LMParams::lambda, ICP::LMParams::lambdaDown, ICP::LMParams::lambdaMax, ICP::LMParams::lambdaMin, ICP::LMParams::lambdaUp, LevenbergMarquardt, ICP::InnerParams::linearSolverType, ICP::InnerParams::lineSearch, ICP::InnerParams::lm, ICP::LineSearchParams::maxIterations, ICP::InnerParams::maxIterations, ICP::InnerParams::preconditionerType, ICP::InnerParams::rotationThreshold, SchurJacobi, ICP::InnerParams::solverType, SparseSchur, ICP::InnerParams::translationThreshold, and ICP::InnerParams::verbose.
commonOptionsToOuterParams()
OuterParams ICP::commonOptionsToOuterParams (const CommonOptions & opts)
Convert CommonOptions to OuterParams.
Definition at line 447 of file CommonOptions.cpp.
References ICP::OuterParams::convergenceTol, ICP::GeometryWeighting::enable_gate, ICP::GeometryWeighting::enable_weight, ICP::OuterParams::maxCorrespondences, ICP::OuterParams::maxIterations, ICP::OuterParams::maxNeighbors, ICP::OuterParams::subsampleX, ICP::OuterParams::subsampleY, ICP::GeometryWeighting::tau, ICP::OuterParams::verbose, and ICP::OuterParams::weighting.
commonOptionsToSessionParams()
SessionParams ICP::commonOptionsToSessionParams (const CommonOptions & opts)
Convert CommonOptions to SessionParams.
Definition at line 468 of file CommonOptions.cpp.
References ICP::SessionParams::backend, Ceres, ICP::SessionParams::fixFirstPose, HandRolled, ICP::SessionParams::useGridPoses, and ICP::SessionParams::verbose.
computeBidirectionalCorrs()
BidirectionalCorrs ICP::computeBidirectionalCorrs (const Grid & source, const Grid & target, const Eigen::Vector3f & rayDir, const Eigen::Isometry3d & srcToTgt, float maxDist, int subsampleX = 1, int subsampleY = 1) inline
Compute bidirectional ray correspondences.
Parameters
source Source grid (rays originate here for forward)
target Target grid (rays originate here for reverse)
rayDir Ray direction in local frame (typically [0,0,-1])
srcToTgt Transform from source to target coordinates
maxDist Maximum ray distance
subsampleX Grid subsampling in X (1=all)
subsampleY Grid subsampling in Y (1=all)
Returns
Forward and reverse correspondences
Definition at line 111 of file Correspondences.h.
References computeRayCorrespondences().
Referenced by solveICP(), solveICPCeres(), solveICPCeresTwoPose(), and solveICPLeft().
computeCostAtPose()
template<typename JacobianPolicy = RayJacobianSimplified> double ICP::computeCostAtPose (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & pose, const Vector3 & rayDir, const GeometryWeighting & weighting)
Compute cost at a given pose.
Evaluates the sum of squared residuals for all correspondences at the specified SE(3) pose. Used for cost evaluation in line search and convergence checking.
Template Parameters
JacobianPolicy Jacobian computation policy (simplified or consistent)
Parameters
fwdCorrs Forward correspondences (source to target)
revCorrs Reverse correspondences (target to source)
pose 7D pose to evaluate [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction for projection
weighting Geometry weighting parameters for incidence handling
Returns
Sum of squared residuals (cost)
Definition at line 74 of file ICPHelpers.h.
computeForwardJacobian()
double ICP::computeForwardJacobian (const Eigen::Vector3f & srcPoint, const Eigen::Vector3f & tgtPoint, const Eigen::Vector3f & tgtNormal, const Eigen::Matrix3d & R, const Eigen::Vector3d & t, const Eigen::Vector3f & rayDir, Eigen::Matrix< double, 1, 6 > & J, const GeometryWeighting & weighting = GeometryWeighting()) inline
Compute forward left-perturbation Jacobian (simplified).
Parameters
srcPoint Source point p in source-local coordinates
tgtPoint Target point q in target-local coordinates
tgtNormal Target normal n in target-local coordinates
R Current rotation estimate
t Current translation estimate
rayDir Ray direction d in target-local coordinates
[out] J 6D Jacobian row vector [d/dt | d/dphi]
weighting Geometry weighting parameters
Returns
Weighted residual value
Definition at line 297 of file JacobiansTangent.h.
References ICP::ForwardRayLeft< RayJacobianSimplified >::Evaluate().
computeModelCostChange()
double ICP::computeModelCostChange (const Tangent6 & delta, const Vector6 & b) inline
Compute the predicted cost reduction from the quadratic model.
For the linearized model: cost(x + delta) cost(x) + delta^T * b + 0.5 * delta^T * H * delta Model cost change = -delta^T * b - 0.5 * delta^T * H * delta
Since we solve H * delta = -b, we have: model_change = -delta^T * b - 0.5 * delta^T * H * delta = delta^T * H * delta - 0.5 * delta^T * H * delta = 0.5 * delta^T * H * delta
But actually for LM, we also need to account for the damping contribution. The full model is: model_change = -delta^T * (b + 0.5 * H_damped * delta) = -delta^T * b - 0.5 * delta^T * H_damped * delta
Since H_damped * delta = -b (from the solve), we get: model_change = -delta^T * b + 0.5 * delta^T * b = -0.5 * delta^T * b
Parameters
delta The computed step
b The gradient vector (J^T * r)
Returns
Predicted cost reduction (positive if cost decreases)
Definition at line 52 of file ICPLM.h.
Referenced by solveInnerLMGainRatio().
computeRayCorrespondences()
std::vector< Correspondence > ICP::computeRayCorrespondences (const Grid & srcGrid, const Grid & tgtGrid, const Eigen::Vector3f & rayDir, const Eigen::Isometry3d & srcToTgt, float maxDist, int subsampleX = 1, int subsampleY = 1) inline
Compute ray-grid correspondences using the grid's intersection backend.
Shoots rays from source grid vertices along a given direction and finds intersections with the target grid mesh.
Parameters
srcGrid Source grid (ray origins)
tgtGrid Target grid (ray target mesh)
rayDir Ray direction in source-local coordinates (normalized)
srcToTgt Transform from source-local to target-local coordinates
maxDist Maximum ray distance
subsampleX Grid subsampling in X (1=all)
subsampleY Grid subsampling in Y (1=all)
Returns
Vector of correspondences
Definition at line 45 of file Correspondences.h.
Referenced by computeBidirectionalCorrs().
computeRelativePose()
Pose7 ICP::computeRelativePose (const Pose7 & poseA, const Pose7 & poseB) inline
Compute relative pose from A to B: T_B^{-1} * T_A This transforms points from A's local frame to B's local frame.
Definition at line 198 of file ICPCeresTwoPose.h.
Referenced by solveICPCeresTwoPose().
computeReverseJacobian()
double ICP::computeReverseJacobian (const Eigen::Vector3f & srcPoint, const Eigen::Vector3f & tgtPoint, const Eigen::Vector3f & tgtNormal, const Eigen::Matrix3d & R, const Eigen::Vector3d & t, const Eigen::Vector3f & rayDir, Eigen::Matrix< double, 1, 6 > & J, const GeometryWeighting & weighting = GeometryWeighting()) inline
Compute reverse left-perturbation Jacobian (simplified).
Parameters
srcPoint Ray origin q in target-local coordinates
tgtPoint Hit point p in source-local coordinates
tgtNormal Normal n_s in source-local coordinates
R Current rotation estimate
t Current translation estimate
rayDir Ray direction d' in source-local coordinates
[out] J 6D Jacobian row vector [d/dt | d/dphi]
weighting Geometry weighting parameters
Returns
Weighted residual value
Definition at line 320 of file JacobiansTangent.h.
References ICP::ReverseRayLeft< RayJacobianSimplified >::Evaluate().
createHeightfieldGrid()
Grid ICP::createHeightfieldGrid (int nx = 45, int ny = 45, float dx = 0.05f, float dy = 0.05f, float amp = 0.10f, float freq = 3.0f)
Create a sinusoidal heightfield grid for testing.
First vertex is at (0, 0). Grid extends to ((nx-1)*dx, (ny-1)*dy).
Parameters
nx Number of vertices in X direction
ny Number of vertices in Y direction
dx Grid spacing in X direction
dy Grid spacing in Y direction
amp Amplitude of sinusoidal height variation
freq Frequency of sinusoidal pattern
Returns
Grid with vertices, marks set (shorter diagonal chosen per quad)
Definition at line 14 of file GridFactory.cpp.
Referenced by createTestGrids().
createIntersectionBackend()
std::unique_ptr< IntersectionBackend > ICP::createIntersectionBackend (IntersectionBackendType type = IntersectionBackendType::Auto)
Factory function to create the appropriate backend.
Parameters
type Backend type to create. If Auto, uses the default set by setDefaultIntersectionBackend() (GridSearch if available).
Returns
The created backend, or nullptr if the requested type is not available.
Definition at line 59 of file BackendFactory.cpp.
References Auto, Embree, and GridSearch.
createTestGrids()
std::pair< Grid, Grid > ICP::createTestGrids (const CommonOptions & opts, bool verbose = false) inline
Create a pair of identical test grids based on options.
Parameters
opts CommonOptions containing grid type and parameters
verbose If true, print grid creation details
Returns
Pair of (source, target) grids
Definition at line 27 of file TestGridUtils.h.
References createHeightfieldGrid(), and createTwoHemispheresGrid().
createTwoHemispheresGrid()
Grid ICP::createTwoHemispheresGrid (int nx = 64, int ny = 64, float dx = 0.2f, float dy = 0.2f, float radius = 2.0f, float separation = 6.0f)
Create a grid with two hemispheres (bumps) for testing.
This geometry constrains all 6 DOF - no rotational symmetry. First vertex is at (0, 0). Grid is centered around ((nx-1)*dx/2, (ny-1)*dy/2).
Parameters
nx Number of vertices in X direction
ny Number of vertices in Y direction
dx Grid spacing in X direction
dy Grid spacing in Y direction
radius Radius of each hemisphere
separation Distance between hemisphere centers
Returns
Grid with vertices, marks set (shorter diagonal chosen per quad)
Definition at line 89 of file GridFactory.cpp.
Referenced by createTestGrids().
dR_dq_mats()
std::array< Matrix3, 4 > ICP::dR_dq_mats (const Quaternion & q) inline
Derivatives of rotation matrix R w.r.t. quaternion components.
Computes \(\frac{\partial R}{\partial q_i}\) for each quaternion component.
Parameters
q Normalized quaternion (will normalize internally)
Returns
Array of four 3x3 matrices: [dR/dx, dR/dy, dR/dz, dR/dw]
Definition at line 523 of file SE3.h.
Referenced by dRTv_dq(), and dRv_dq().
dRTv_dq()
Matrix3x4 ICP::dRTv_dq (const Quaternion & q, const Vector3 & v) inline
Derivative of R(q)^T * v w.r.t. quaternion q.
Computes \(\frac{\partial (R^\top \mathbf{v})}{\partial \mathbf{q}}\).
Parameters
q Quaternion
v 3D vector
Returns
3x4 matrix: [d(R^T v)/dx, d(R^T v)/dy, d(R^T v)/dz, d(R^T v)/dw]
Definition at line 570 of file SE3.h.
References dR_dq_mats().
dRv_dq()
Matrix3x4 ICP::dRv_dq (const Quaternion & q, const Vector3 & v) inline
Derivative of R(q) * v w.r.t. quaternion q.
Computes \(\frac{\partial (R \mathbf{v})}{\partial \mathbf{q}}\).
Parameters
q Quaternion
v 3D vector
Returns
3x4 matrix: [d(Rv)/dx, d(Rv)/dy, d(Rv)/dz, d(Rv)/dw]
Definition at line 550 of file SE3.h.
References dR_dq_mats().
getDefaultIntersectionBackend()
IntersectionBackendType ICP::getDefaultIntersectionBackend ()
Get the current default intersection backend type.
Definition at line 31 of file BackendFactory.cpp.
identityPose()
Pose7 ICP::identityPose () inline
Create identity pose.
Returns
Pose7 with identity rotation and zero translation: [0, 0, 0, 1, 0, 0, 0]
Definition at line 123 of file EigenUtils.h.
isBackendAvailable()
bool ICP::isBackendAvailable (IntersectionBackendType type)
Check if a backend type is available (compiled in).
Definition at line 36 of file BackendFactory.cpp.
References Auto, Embree, and GridSearch.
isDeltaConverged()
bool ICP::isDeltaConverged (const Tangent6 & delta, double transThreshold, double rotThreshold) inline
Check if delta is below convergence thresholds.
Uses separate thresholds for translation and rotation components to determine if the optimization has converged.
Parameters
delta Tangent space update [v_x, v_y, v_z, w_x, w_y, w_z]
transThreshold Translation threshold (same units as data, e.g., mm)
rotThreshold Rotation threshold (radians)
Returns
True if both translation and rotation norms are below their thresholds
Definition at line 121 of file ICPHelpers.h.
Referenced by solveInnerGN(), solveInnerGNLeft(), solveInnerLMGainRatio(), and solveInnerLMSimple().
isLinearSolverAvailable()
bool ICP::isLinearSolverAvailable (const std::string & solverName) inline
Check if a linear solver type is available.
Parameters
solverName The solver name (e.g., "cuda-dense", "cuda-sparse")
Returns
True if the solver is available
Definition at line 43 of file CeresCapabilities.h.
References hasCudaSupport(), and hasSuiteSparseSupport().
isometryToPose7()
Pose7 ICP::isometryToPose7 (const Eigen::Isometry3d & iso) inline
Convert Isometry3d to Pose7.
Parameters
iso Input isometry (rotation + translation)
Returns
Pose7 [qx, qy, qz, qw, tx, ty, tz]
Definition at line 135 of file EigenUtils.h.
jacobian7Dto6D()
Eigen::Matrix< double, 1, 6 > ICP::jacobian7Dto6D (const double * J7, const double * x) inline
Project 7D ambient Jacobian to 6D local (tangent space) Jacobian.
Computes \(J_{\text{local}} = J_{\text{ambient}} \cdot P(x)\) where \(P(x)\) is the Plus Jacobian at pose \(x\).
Note
This is a pullback through the Plus chart, not a Euclidean projection
Parameters
J7 7D ambient Jacobian (1x7 row vector)
x 7D pose [qx, qy, qz, qw, tx, ty, tz]
Returns
6D local Jacobian (1x6 row vector)
Definition at line 502 of file SE3.h.
References plusJacobian7x6().
lineSearch()
template<typename JacobianPolicy = RayJacobianSimplified> double ICP::lineSearch (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & pose, const Tangent6 & delta, double currentCost, const Vector3 & rayDir, const GeometryWeighting & weighting, const LineSearchParams & params, double rotationScale = 1.0)
Backtracking line search to find optimal step size.
Implements simple backtracking line search to find a step size that reduces the cost. Starts with alpha=1 and reduces by factor beta until cost decreases or maximum iterations reached.
Template Parameters
JacobianPolicy Jacobian computation policy (simplified or consistent)
Parameters
fwdCorrs Forward correspondences (source to target)
revCorrs Reverse correspondences (target to source)
pose Current pose [qx, qy, qz, qw, tx, ty, tz]
delta Full step direction in tangent space
currentCost Cost at current pose (for comparison)
rayDir Ray direction for projection
weighting Geometry weighting parameters
params Line search configuration (alpha, beta, maxIterations)
rotationScale Characteristic length for rotation scaling (1.0 = no scaling)
Returns
Optimal step size alpha in (0, 1]
Definition at line 173 of file ICPHelpers.h.
References ICP::LineSearchParams::alpha, applyDeltaAndNormalize(), ICP::LineSearchParams::beta, and ICP::LineSearchParams::maxIterations.
nielsenRadiusFactor()
double ICP::nielsenRadiusFactor (double rho) inline
Compute Nielsen's trust region radius update factor.
From "Methods for Non-Linear Least Squares Problems" by Madsen, Nielsen, Tingleff. radius_new = radius / max(1/3, 1 - (2*rho - 1)^3)
This formula:
When rho 1 (perfect model): expands radius by factor of 3
When rho 0.5: keeps radius roughly the same
When rho close to 0: contracts radius
Parameters
rho Gain ratio (actual_reduction / model_reduction)
Returns
Factor to divide radius by (< 1 expands, > 1 contracts)
Definition at line 73 of file ICPLM.h.
Referenced by solveInnerLMGainRatio().
parseGridIndices()
std::vector< int > ICP::parseGridIndices (const std::string & str)
Parse grid indices from a string. Supports: "0,1,3" or "0-9" or "0-5,10,15-20" or "" (empty = all) Returns sorted, deduplicated indices.
Definition at line 24 of file CommonOptions.cpp.
perturbPoseRotation()
void ICP::perturbPoseRotation (Pose7 & pose, double stddevDeg, std::mt19937 & gen) inline
Perturb the rotation component of a Pose7 in-place.
Parameters
pose Pose to modify [qx, qy, qz, qw, tx, ty, tz]
stddevDeg Standard deviation of rotation noise in degrees
gen Random number generator
Definition at line 227 of file EigenUtils.h.
References perturbRotation().
perturbPoseTranslation()
void ICP::perturbPoseTranslation (Pose7 & pose, double stddev, std::mt19937 & gen) inline
Perturb the translation component of a Pose7 in-place.
Parameters
pose Pose to modify [qx, qy, qz, qw, tx, ty, tz]
stddev Standard deviation of translation noise
gen Random number generator
Definition at line 246 of file EigenUtils.h.
perturbRotation()
Eigen::Quaterniond ICP::perturbRotation (const Eigen::Quaterniond & q, double stddevDeg, std::mt19937 & gen) inline
Add random rotation noise to a quaternion.
Applies a random rotation around a random axis with angle drawn from a Gaussian distribution.
Parameters
q Original quaternion (unit)
stddevDeg Standard deviation of rotation angle in degrees
gen Random number generator
Returns
Perturbed quaternion (normalized)
Definition at line 208 of file EigenUtils.h.
Referenced by perturbPoseRotation().
plusJacobian7x6()
Matrix7x6 ICP::plusJacobian7x6 (const Pose7 & x) inline
SE(3) chart Jacobian P(x) for the right-multiplicative Plus operation.
Let Plus(x, delta) apply a body-frame (right) perturbation: T_new = T(x) * Exp(delta^), with delta = (v, w) R^6.
This function returns the chart Jacobian evaluated at the linearization point: P(x) = Plus(x, delta) / delta |_{delta = 0} (size 76), mapping a small tangent increment R^6 to a first-order change in the 7D ambient parameterization (quaternion + translation).
Block structure at delta = 0:
Translation part: t/v = R(q) because V(0) = I and t_new = t + R * V(w) * v. t/w = 0 at the expansion point, since this term is proportional to v (and v = 0 at delta = 0 in the partial derivative).
Quaternion part (right perturbation): q_new = q Exp(w). Using the small-angle approximation Exp(w) [1, 0.5 w] in quaternion form, we obtain (with q = [v_q, s]): v_q/w = 0.5 (s I + [v_q]_), s /w = -0.5 v_q^T.
Sign convention note:
The above expressions are for right-multiplication (q_new = q q).
If using left-multiplication (q_new = q q), the cross-term changes sign (the skew term appears with the opposite sign).
Quaternion renormalization is treated as a no-op at first order.
Note
For the full 7x6 SE(3) chart Jacobian away from the linearization point, see SE(3) Full Chart Jacobian (Right-Multiplicative).
Parameters
x Current pose [qx, qy, qz, qw, tx, ty, tz] (quaternion stored as x,y,z,w)
Returns
76 chart Jacobian P(x) evaluated at delta = 0
Definition at line 375 of file SE3.h.
References skew().
Referenced by buildNormalEquations(), jacobian7Dto6D(), and plusJacobian7x6Scaled().
plusJacobian7x6Scaled()
Matrix7x6 ICP::plusJacobian7x6Scaled (const Pose7 & x, double rotationScale) inline
SE(3) chart Jacobian with rotation scaling for conditioning.
Returns the chart Jacobian for the scaled Plus operation:
\[ P_{\text{scaled}}(x) = P(x) \, S \]
where \(S = \text{diag}(I_3, L \cdot I_3)\) scales the rotation columns.
At the expansion point \(\delta = 0\):
\[ P_{\text{scaled}}(x) = \begin{bmatrix} 0 & L \cdot \frac{\partial \mathbf{q}}{\partial \boldsymbol{\omega}} \\ R & 0 \end{bmatrix} \]
Parameters
x Current pose [qx, qy, qz, qw, tx, ty, tz]
rotationScale Characteristic length L (scales rotation columns)
Returns
7x6 chart Jacobian P_scaled(x) evaluated at delta = 0
See also
Effective Conditioning via Manifold Scaling for mathematical background
Definition at line 479 of file SE3.h.
References plusJacobian7x6().
Referenced by buildNormalEquations().
pose7ToIsometry()
Eigen::Isometry3d ICP::pose7ToIsometry (const Pose7 & pose) inline
Convert Pose7 to Isometry3d.
Parameters
pose Input pose [qx, qy, qz, qw, tx, ty, tz]
Returns
Isometry3d with rotation and translation
Definition at line 150 of file EigenUtils.h.
Referenced by buildEdges(), solveICP(), solveICPCeres(), solveICPCeresTwoPose(), and solveICPLeft().
poseToString()
std::string ICP::poseToString (const Pose7 & pose) inline
Format a Pose7 as a human-readable string.
Output format: "rot=X.XX deg around [ax, ay, az], t=[tx, ty, tz]"
Parameters
pose SE(3) pose [qx, qy, qz, qw, tx, ty, tz]
precision Decimal precision for floating-point values (default: 2 for rotation, 6 for translation)
Returns
Formatted string
Definition at line 594 of file SE3.h.
printCommonConfig()
void ICP::printCommonConfig (const CommonOptions & opts)
Print common ICP configuration to stdout.
Displays backend, jacobian policy, outer/inner loop params, and geometry weighting.
Definition at line 480 of file CommonOptions.cpp.
printConnectivityMatrix()
void ICP::printConnectivityMatrix (const std::vector< std::vector< int > > & counts)
Print correspondence connectivity matrix.
Shows how many correspondences exist between each grid pair. Diagonal shows '-', zero entries show '.'.
Parameters
counts NxN matrix of correspondence counts
Definition at line 365 of file MultiViewICP.cpp.
Referenced by runMultiViewICP().
printResultsTable()
void ICP::printResultsTable (const std::vector< Pose7 > & finalPoses, const std::vector< Pose7 > & initialPoses, const std::vector< Pose7 > & groundTruth)
Print per-grid results table comparing initial and final errors.
Shows translation and rotation error for each grid vs ground truth, comparing initial (perturbed) and final (optimized) poses.
Parameters
finalPoses Final optimized poses
initialPoses Initial (perturbed) poses before ICP
groundTruth Ground truth poses
Definition at line 393 of file MultiViewICP.cpp.
quatExpSO3()
Quaternion ICP::quatExpSO3 (const Vector3 & w) inline
SO(3) exponential map in quaternion form.
Computes the unit quaternion corresponding to \(\exp([\boldsymbol{\omega}]_\times)\):
\[ \mathbf{q} = \begin{bmatrix} w \\ \mathbf{u} \end{bmatrix} = \begin{bmatrix} \cos(\theta/2) \\ \sin(\theta/2) \hat{\mathbf{a}} \end{bmatrix} \]
where \(\theta = \|\boldsymbol{\omega}\|\) is the rotation angle and \(\hat{\mathbf{a}} = \boldsymbol{\omega}/\theta\) is the unit rotation axis.
For small angles (\(\theta < 10^{-12}\)), uses first-order Taylor expansion.
Note
Eigen stores quaternion coeffs as [x, y, z, w] internally.
Parameters
w Rotation vector (axis-angle representation)
Returns
Unit quaternion (w, x, y, z)
Definition at line 215 of file SE3.h.
References kSmallAngleThreshold.
Referenced by se3Plus(), se3PlusLeft(), and se3PlusScaled().
randomQuaternion()
Quaternion ICP::randomQuaternion (std::mt19937 & rng) inline
Generate a random unit quaternion.
Parameters
rng Random number generator
Returns
Normalized quaternion with uniform distribution on SO(3)
Definition at line 83 of file EigenUtils.h.
randomUnitVector()
template<int N> Eigen::Matrix< double, N, 1 > ICP::randomUnitVector (std::mt19937 & rng)
Generate a random unit vector in R^N.
Template Parameters
N Dimension of the vector
Parameters
rng Random number generator
Returns
Normalized N-dimensional vector
Definition at line 98 of file EigenUtils.h.
randomVector3()
Vector3 ICP::randomVector3 (std::mt19937 & rng, double scale = 1.0) inline
Generate a random 3D vector with uniform distribution.
Parameters
rng Random number generator
scale Each component is drawn from [-scale, scale]
Returns
Random 3D vector
Definition at line 113 of file EigenUtils.h.
rotationPose()
Pose7 ICP::rotationPose (const Vector3 & axisAngle) inline
Create pose from axis-angle rotation (no translation).
Parameters
axisAngle Rotation vector (axis * angle in radians)
Returns
Pose7 with zero translation
Definition at line 179 of file EigenUtils.h.
runMultiViewICP()
MultiViewICPResult ICP::runMultiViewICP (std::vector< Grid > & grids, const SessionParams & session, const OuterParams & outer, const InnerParams & inner)
Run multi-view ICP on a set of grids.
Optimizes grid.pose for each grid in place.
Parameters
grids Grids with initial poses in grid.pose (modified in place)
session Session parameters (fixFirstPose, verbose)
outer Outer loop parameters (correspondences, weighting)
inner Inner loop parameters (solver type, iterations)
Returns
Result with statistics (final poses also in grid.pose)
Definition at line 143 of file MultiViewICP.cpp.
References buildCorrespondenceMatrix(), buildEdges(), Consistent, ICP::OuterParams::convergenceTol, DenseQR, ICP::GeometryWeighting::enable_gate, ICP::SessionParams::fixFirstPose, ICP::InnerParams::jacobianPolicy, ICP::InnerParams::linearSolverType, ICP::OuterParams::maxIterations, printConnectivityMatrix(), ICP::OuterParams::rayDir, ICP::GeometryWeighting::tau, toCeresSolverOptions(), ICP::SessionParams::verbose, ICP::OuterParams::verbose, and ICP::OuterParams::weighting.
se3Plus()
Pose7 ICP::se3Plus (const Pose7 & x, const Tangent6 & delta) inline
SE(3) Plus operation using right-multiplication (body-frame perturbation).
Applies a tangent-space increment via the SE(3) exponential map:
\[ T_{\text{new}} = T \cdot \exp(\widehat{\delta\boldsymbol{\xi}}), \quad \delta\boldsymbol{\xi} = (\mathbf{v}, \boldsymbol{\omega}) \in \mathbb{R}^6 \]
With \(\Delta R = \exp([\boldsymbol{\omega}]_\times)\) and the SE(3) coupling matrix \(V(\boldsymbol{\omega})\) (SO(3) left Jacobian), the component update is:
\[ R_{\text{new}} = R \cdot \Delta R, \qquad \mathbf{t}_{\text{new}} = \mathbf{t} + R \cdot V(\boldsymbol{\omega}) \cdot \mathbf{v}. \]
Gotchas / conventions:
Right (body-frame) perturbation: the quaternion update is \(\mathbf{q}_{\text{new}} = \mathbf{q} \otimes \delta\mathbf{q}\) (not \(\delta\mathbf{q} \otimes \mathbf{q}\)).
Translation uses the current rotation: the translational increment is rotated by the current \(R(\mathbf{q})\) (not \(R(\mathbf{q}_{\text{new}})\)).
Quaternion sign ambiguity: \(\mathbf{q}\) and \(-\mathbf{q}\) represent the same rotation. The update may flip the quaternion sign without affecting \(R(\mathbf{q})\) or any geometric quantity.
Parameters
x Current pose [qx, qy, qz, qw, tx, ty, tz]
delta Tangent increment [v_x, v_y, v_z, w_x, w_y, w_z]
Returns
Updated pose
Definition at line 304 of file SE3.h.
References quatExpSO3(), and Vso3().
Referenced by applyDeltaAndNormalize().
se3PlusLeft()
Pose7 ICP::se3PlusLeft (const Pose7 & x, const Tangent6 & delta) inline
SE(3) Plus operation using left-multiplication (space-frame perturbation).
Applies a tangent-space increment via left multiplication: T_new = Exp(delta) * T
In components: R_new = deltaR * R t_new = deltaR * t + V(w) * v
Parameters
x Current pose [qx, qy, qz, qw, tx, ty, tz]
delta Tangent increment [v_x, v_y, v_z, w_x, w_y, w_z]
Returns
Updated pose
Definition at line 52 of file ICPSolverLeft.h.
References quatExpSO3(), and Vso3().
Referenced by applyDeltaLeftAndNormalize().
se3PlusScaled()
Pose7 ICP::se3PlusScaled (const Pose7 & x, const Tangent6 & delta, double rotationScale) inline
SE(3) Plus operation with rotation scaling for conditioning.
This is a modified Plus operation that applies a characteristic length scale to the rotation component, improving the conditioning of the optimization problem when translation and rotation have very different scales.
The scaled tangent vector is:
\[ \delta' = S \delta, \quad S = \begin{bmatrix} I_3 & 0 \\ 0 & L I_3 \end{bmatrix} \]
This makes "1 unit of rotation (radian)" comparable to "L units of translation".
Note
This is a change of variables, not a change of the objective function. The final result is invariant; only convergence speed is affected.
Parameters
x Current pose [qx, qy, qz, qw, tx, ty, tz]
delta Tangent increment [v_x, v_y, v_z, w_x, w_y, w_z]
rotationScale Characteristic length L (scales rotation columns)
Returns
Updated pose
See also
Effective Conditioning via Manifold Scaling for mathematical background
Definition at line 428 of file SE3.h.
References quatExpSO3(), and Vso3().
Referenced by applyDeltaAndNormalize().
setDefaultIntersectionBackend()
void ICP::setDefaultIntersectionBackend (IntersectionBackendType type)
Set the default intersection backend type. Affects all subsequent calls to createIntersectionBackend() with Auto type. Thread-safe.
Definition at line 26 of file BackendFactory.cpp.
skew()
Matrix3 ICP::skew (const Vector3 & w) inline
Compute the skew-symmetric matrix from a 3D vector.
Creates the matrix \([\mathbf{w}]_\times\) such that \([\mathbf{w}]_\times \mathbf{v} = \mathbf{w} \times \mathbf{v}\):
\[ [\mathbf{w}]_\times = \begin{bmatrix} 0 & -w_z & w_y \\ w_z & 0 & -w_x \\ -w_y & w_x & 0 \end{bmatrix} \]
Parameters
w Input 3D vector
Returns
3x3 skew-symmetric matrix
Definition at line 189 of file SE3.h.
Referenced by plusJacobian7x6(), and Vso3().
solveICP()
template<typename JacobianPolicy = RayJacobianSimplified> ICPResult ICP::solveICP (const Grid & source, const Grid & target, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & innerParams = InnerParams(), const OuterParams & outerParams = OuterParams())
Full ICP solver with outer loop (recompute correspondences) and inner loop.
Parameters
source Source grid
target Target grid
initialPose Initial pose estimate
rayDir Ray direction in local frame (typically [0,0,-1])
weighting Geometry weighting parameters
innerParams Inner solver parameters
outerParams Outer loop parameters
Returns
ICP result with final pose and statistics
Definition at line 182 of file ICPSolver.h.
References computeBidirectionalCorrs(), ICP::OuterParams::maxIterations, and pose7ToIsometry().
solveICPCeres()
template<typename JacobianPolicy = RayJacobianSimplified> CeresICPResult ICP::solveICPCeres (const Grid & source, const Grid & target, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & innerParams = InnerParams(), const OuterParams & outerParams = OuterParams())
Full Ceres ICP solver with outer loop.
Parameters
source Source grid
target Target grid
initialPose Initial pose estimate
rayDir Ray direction in local frame (typically [0,0,-1])
weighting Geometry weighting parameters
innerParams Inner solver parameters
outerParams Outer loop parameters
Template Parameters
JacobianPolicy Jacobian computation policy (default: RayJacobianSimplified)
Returns
ICP result with final pose and statistics
Definition at line 227 of file ICPCeresSolver.h.
References computeBidirectionalCorrs(), ICP::OuterParams::maxIterations, and pose7ToIsometry().
solveICPCeresTwoPose()
template<typename JacobianPolicy = RayJacobianSimplified> CeresTwoPoseResult ICP::solveICPCeresTwoPose (const Grid & gridA, const Grid & gridB, const Pose7 & initialPoseA, const Pose7 & initialPoseB, const Vector3 & rayDir, const GeometryWeighting & weighting, const InnerParams & innerParams, const OuterParams & outerParams, bool fixPoseA = false)
Full two-pose Ceres ICP solver with outer loop.
Parameters
gridA First grid
gridB Second grid
initialPoseA Initial pose for grid A
initialPoseB Initial pose for grid B
rayDir Ray direction in local frame (typically [0,0,-1])
weighting Geometry weighting parameters
innerParams Inner loop parameters (converted to Ceres options)
outerParams Outer loop parameters
fixPoseA If true, hold pose A fixed
Returns
ICP result with final poses and statistics
Definition at line 240 of file ICPCeresTwoPose.h.
References computeBidirectionalCorrs(), computeRelativePose(), ICP::OuterParams::convergenceTol, ICP::OuterParams::maxDist, ICP::OuterParams::maxIterations, pose7ToIsometry(), ICP::OuterParams::subsampleX, ICP::OuterParams::subsampleY, toCeresSolverOptions(), and ICP::OuterParams::verbose.
solveInner()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInner (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Inner solver: iterate with fixed correspondences until convergence.
Dispatches to either Gauss-Newton or Levenberg-Marquardt based on params.solverType.
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (same for both, typically [0,0,-1])
weighting Geometry weighting parameters
params Inner solver parameters (iterations, tolerance, damping)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 150 of file ICPSolver.h.
References GaussNewton, and LevenbergMarquardt.
solveInnerCeres()
template<typename JacobianPolicy = RayJacobianSimplified> CeresInnerSolveResult ICP::solveInnerCeres (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & innerParams = InnerParams())
Inner solver using Ceres: build problem with fixed correspondences.
Processes bidirectional correspondences:
Forward: rays from source to target (ForwardRayCost)
Reverse: rays from target to source (ReverseRayCost)
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (typically [0,0,-1])
weighting Geometry weighting parameters
innerParams Inner solver parameters (iterations, tolerances, etc.)
Template Parameters
JacobianPolicy Jacobian computation policy (default: RayJacobianSimplified)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 104 of file ICPCeresSolver.h.
References toCeresSolverOptions().
solveInnerCeresTwoPose()
template<typename JacobianPolicy = RayJacobianSimplified> CeresTwoPoseInnerResult ICP::solveInnerCeresTwoPose (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPoseA, const Pose7 & initialPoseB, const Vector3 & rayDirA, const Vector3 & rayDirB, const GeometryWeighting & weighting, const ceres::Solver::Options & ceresOptions, bool fixPoseA = false)
Inner solver using Ceres for two-pose optimization.
Processes bidirectional correspondences:
Forward: rays from grid A to grid B (ForwardRayCostTwoPose)
Reverse: rays from grid B to grid A (ReverseRayCostTwoPose)
Parameters
fwdCorrs Forward correspondences (AB rays)
revCorrs Reverse correspondences (BA rays)
initialPoseA Initial 7D pose for grid A [qx, qy, qz, qw, tx, ty, tz]
initialPoseB Initial 7D pose for grid B [qx, qy, qz, qw, tx, ty, tz]
rayDirA Ray direction in grid A frame (typically [0,0,-1])
rayDirB Ray direction in grid B frame (typically [0,0,-1])
weighting Geometry weighting parameters
ceresOptions Ceres solver options
fixPoseA If true, hold pose A fixed (only optimize B)
Returns
Final poses, RMS, iteration count, convergence status
Definition at line 83 of file ICPCeresTwoPose.h.
References ICP::GeometryWeighting::enable_gate, and ICP::GeometryWeighting::tau.
solveInnerGN()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInnerGN (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Gauss-Newton inner solver with optional line search.
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (same for both, typically [0,0,-1])
weighting Geometry weighting parameters
params Inner solver parameters (iterations, tolerance, damping, line search)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 54 of file ICPSolver.h.
References applyDeltaAndNormalize(), ICP::InnerSolveResult::converged, isDeltaConverged(), ICP::InnerSolveResult::iterations, ICP::InnerSolveResult::pose, ICP::InnerSolveResult::rms, and ICP::InnerSolveResult::valid_count.
solveInnerGNLeft()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInnerGNLeft (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Gauss-Newton inner solver using left-perturbation.
Uses left multiplication for pose updates: T_new = Exp(delta) * T
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in source frame
weighting Geometry weighting parameters
params Inner solver parameters
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 239 of file ICPSolverLeft.h.
References applyDeltaLeftAndNormalize(), ICP::InnerSolveResult::converged, isDeltaConverged(), ICP::InnerSolveResult::iterations, ICP::InnerSolveResult::pose, ICP::InnerSolveResult::rms, and ICP::InnerSolveResult::valid_count.
solveInnerLM()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInnerLM (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Levenberg-Marquardt inner solver dispatcher.
Dispatches to either Simple or GainRatio strategy based on params.lm.strategy.
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (same for both, typically [0,0,-1])
weighting Geometry weighting parameters
params Inner solver parameters (iterations, tolerance, LM settings)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 467 of file ICPLM.h.
References GainRatio, and Simple.
solveInnerLMGainRatio()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInnerLMGainRatio (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Levenberg-Marquardt inner solver with gain ratio strategy (Ceres-style).
Uses the gain ratio rho = actual_reduction / model_reduction to:
Decide step acceptance: accept if rho > minRelativeDecrease
Adapt trust region: radius = radius / nielsenFactor(rho)
Double decrease factor on successive rejections
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (same for both, typically [0,0,-1])
weighting Geometry weighting parameters
params Inner solver parameters (iterations, tolerance, LM settings)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 100 of file ICPLM.h.
References applyDeltaAndNormalize(), computeModelCostChange(), ICP::InnerSolveResult::converged, isDeltaConverged(), ICP::InnerSolveResult::iterations, nielsenRadiusFactor(), ICP::InnerSolveResult::pose, ICP::InnerSolveResult::rms, and ICP::InnerSolveResult::valid_count.
solveInnerLMSimple()
template<typename JacobianPolicy = RayJacobianSimplified> InnerSolveResult ICP::solveInnerLMSimple (const std::vector< Correspondence > & fwdCorrs, const std::vector< Correspondence > & revCorrs, const Pose7 & initialPose, const Vector3 & rayDir, const GeometryWeighting & weighting = GeometryWeighting(), const InnerParams & params = InnerParams())
Levenberg-Marquardt inner solver with simple adaptive damping.
When params.lm.fixedLambda=true: uses constant lambda (like damped Gauss-Newton). When params.lm.fixedLambda=false: adapts lambda based on cost reduction.
Uses simple cost comparison for step acceptance (like MultiRegistration):
If trialCost < currentCost: accept step, decrease lambda
Otherwise: reject step, increase lambda, retry with same H and b
Parameters
fwdCorrs Forward correspondences (sourcetarget rays)
revCorrs Reverse correspondences (targetsource rays)
initialPose Initial 7D pose [qx, qy, qz, qw, tx, ty, tz]
rayDir Ray direction in local frame (same for both, typically [0,0,-1])
weighting Geometry weighting parameters
params Inner solver parameters (iterations, tolerance, LM settings)
Returns
Final pose, RMS, iteration count, convergence status
Definition at line 267 of file ICPLM.h.
References applyDeltaAndNormalize(), ICP::InnerSolveResult::converged, isDeltaConverged(), ICP::InnerSolveResult::iterations, ICP::InnerSolveResult::pose, ICP::InnerSolveResult::rms, and ICP::InnerSolveResult::valid_count.
toCeresSolverOptions()
ceres::Solver::Options ICP::toCeresSolverOptions (const InnerParams & inner) inline
Convert InnerParams to Ceres solver options.
Maps the ICP parameter structure to Ceres-specific options. Used internally by the Ceres backend.
Parameters
inner Inner loop parameters to convert
Returns
Configured Ceres solver options
Definition at line 386 of file ICPParams.h.
References CudaDenseCholesky, CudaSparseCholesky, DenseQR, DenseSchur, Identity, IterativeSchur, Jacobi, ICP::LMParams::lambda, ICP::LMParams::lambdaMin, LevenbergMarquardt, ICP::InnerParams::linearSolverType, ICP::InnerParams::lm, ICP::InnerParams::maxIterations, ICP::InnerParams::preconditionerType, SchurJacobi, ICP::InnerParams::solverType, SparseSchur, ICP::InnerParams::translationThreshold, and ICP::InnerParams::verbose.
Referenced by runMultiViewICP(), solveICPCeresTwoPose(), and solveInnerCeres().
translationPose()
Pose7 ICP::translationPose (double tx, double ty, double tz) inline
Create pose from translation only (identity rotation).
Parameters
tx Translation x
ty Translation y
tz Translation z
Returns
Pose7 with identity rotation
Definition at line 167 of file EigenUtils.h.
Vso3()
Matrix3 ICP::Vso3 (const Vector3 & w) inline
Left Jacobian of SO(3).
Computes the matrix \(V\) used in the SE(3) Plus operation: \(\mathbf{t}_{\text{new}} = \mathbf{t} + R \cdot V \cdot \mathbf{v}\)
\[ V = I + B \cdot [\boldsymbol{\omega}]_\times + C \cdot [\boldsymbol{\omega}]_\times^2 \]
where \(\theta = \|\boldsymbol{\omega}\|\) and:
\(B = (1 - \cos\theta) / \theta^2\)
\(C = (1 - \sin\theta / \theta) / \theta^2\)
For small angles (\(\theta < 10^{-12}\)), uses \(V \approx I + \frac{1}{2}[\boldsymbol{\omega}]_\times\).
Parameters
w Rotation vector
Returns
3x3 left Jacobian matrix [Vso3]
Definition at line 252 of file SE3.h.
References kSmallAngleThreshold, and skew().
Referenced by se3Plus(), se3PlusLeft(), and se3PlusScaled().
Variable Documentation
kSmallAngleThreshold
constexpr double ICP::kSmallAngleThreshold = 1e-12 constexpr
Small angle threshold for Taylor expansion in SO(3)/SE(3) operations.
When \(\|\boldsymbol{\omega}\| < \epsilon\), first-order Taylor expansions are used to avoid numerical instability in trigonometric functions.
Definition at line 167 of file SE3.h.
Referenced by quatExpSO3(), and Vso3().