QuaternionICP: ICP/TriangulationMarks.h File Reference
TriangulationMarks.h File Reference
C++ wrapper for GridSearch triangulation mark constants.
#include <ICP/Config.h>
#include <cstdint>
Typedefs
using TriangulationMarks::Mark = GridSearchMark
Mark type for triangulation bit flags.
Functions
bool TriangulationMarks::IsValidVertex (Mark mark)
Check if a mark indicates a valid vertex.
bool TriangulationMarks::HasUpperTriangle (Mark mark)
Check if a quad has an upper triangle.
bool TriangulationMarks::HasLowerTriangle (Mark mark)
Check if a quad has a lower triangle.
int TriangulationMarks::GetVertexIndexFromFacetId (int facetId)
Extract vertex index from a facet ID.
int TriangulationMarks::GetFacetConfigFromFacetId (int facetId)
Extract facet configuration from a facet ID.
Variables
Individual Bit Flags
constexpr Mark TriangulationMarks::MarkPointValid = (1 << 0)
Point has valid depth data.
constexpr Mark TriangulationMarks::MarkPointVertex = (1 << 1)
Point is a vertex in the triangulation.
constexpr Mark TriangulationMarks::MarkQuadLower = (1 << 3)
Quad has a lower triangle.
constexpr Mark TriangulationMarks::MarkQuadUpper = (1 << 4)
Quad has an upper triangle.
constexpr Mark TriangulationMarks::MarkQuadDiagonal = (1 << 5)
Quad diagonal orientation flag.
Combined Masks
constexpr Mark TriangulationMarks::MarkValidVertex = MarkPointValid | MarkPointVertex
Combined mask for valid vertex points.
constexpr Mark TriangulationMarks::MarkAnyTriangle = MarkQuadUpper | MarkQuadLower
Combined mask for any triangle (upper or lower).
Facet Configuration Constants
constexpr int TriangulationMarks::FacetConfigLL = 0x00000
Lower-left configuration.
constexpr int TriangulationMarks::FacetConfigUR = 0x10000
Upper-right configuration.
constexpr int TriangulationMarks::FacetConfigLR = 0x20000
Lower-right configuration.
constexpr int TriangulationMarks::FacetConfigUL = 0x30000
Upper-left configuration.
constexpr int TriangulationMarks::FacetConfigMask = 0x30000
Mask for extracting config bits.
Detailed Description
C++ wrapper for GridSearch triangulation mark constants.
Wraps the C API from GridSearch/GridSearchTypesC.h with C++ conveniences.
Grid Triangulation
Each grid cell (quad) is split into two triangles. The mark bits encode:
Whether a point is valid
Whether it's a vertex of the triangulation
Which triangles (upper/lower) exist in the quad
Facet ID Encoding
A facet ID encodes both the vertex index and the triangle configuration:
Lower bits: vertex index in the grid
Upper bits: facet configuration (LL, UR, LR, UL)
Definition in file TriangulationMarks.h.
Function Documentation
GetFacetConfigFromFacetId()
int TriangulationMarks::GetFacetConfigFromFacetId (int facetId) inline
Extract facet configuration from a facet ID.
Parameters
facetId The encoded facet identifier
Returns
The facet configuration (LL, UR, LR, or UL)
Definition at line 139 of file TriangulationMarks.h.
References TriangulationMarks::FacetConfigMask, and TriangulationMarks::GetFacetConfigFromFacetId().
Referenced by TriangulationMarks::GetFacetConfigFromFacetId().
GetVertexIndexFromFacetId()
int TriangulationMarks::GetVertexIndexFromFacetId (int facetId) inline
Extract vertex index from a facet ID.
Parameters
facetId The encoded facet identifier
Returns
The vertex index (configuration bits masked out)
Definition at line 129 of file TriangulationMarks.h.
References TriangulationMarks::GetVertexIndexFromFacetId().
Referenced by TriangulationMarks::GetVertexIndexFromFacetId().
HasLowerTriangle()
bool TriangulationMarks::HasLowerTriangle (Mark mark) inline
Check if a quad has a lower triangle.
Parameters
mark The triangulation mark to check
Returns
True if the lower triangle exists
Definition at line 119 of file TriangulationMarks.h.
References TriangulationMarks::HasLowerTriangle(), and TriangulationMarks::MarkQuadLower.
Referenced by TriangulationMarks::HasLowerTriangle().
HasUpperTriangle()
bool TriangulationMarks::HasUpperTriangle (Mark mark) inline
Check if a quad has an upper triangle.
Parameters
mark The triangulation mark to check
Returns
True if the upper triangle exists
Definition at line 109 of file TriangulationMarks.h.
References TriangulationMarks::HasUpperTriangle(), and TriangulationMarks::MarkQuadUpper.
Referenced by TriangulationMarks::HasUpperTriangle().
IsValidVertex()
bool TriangulationMarks::IsValidVertex (Mark mark) inline
Check if a mark indicates a valid vertex.
Parameters
mark The triangulation mark to check
Returns
True if the point is both valid and a vertex
Definition at line 99 of file TriangulationMarks.h.
References TriangulationMarks::IsValidVertex(), and TriangulationMarks::MarkValidVertex.
Referenced by TriangulationMarks::IsValidVertex().