var searchData=
[
  ['r_20t_20rotation_0',['Quaternion w.r.t. Rotation',['../se3_full_chart_jacobian.html#se3_full_dq_dw',1,'']]],
  ['r_20t_20rotation_20away_20from_20delta_200_1',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['r_20t_20translation_2',['Translation w.r.t. Translation',['../se3_full_chart_jacobian.html#se3_full_dt_dv',1,'']]],
  ['r_20w_20c_20a_20c_3',['4) Full derivative of r = w(c) * a/c',['../md_Doc_2JacobianPedantic.html#autotoc_md39',1,'']]],
  ['randomquaternion_4',['randomQuaternion',['../namespaceICP.html#a8fa80a2491dc261e4a2547f76b1d117c',1,'ICP']]],
  ['randomunitvector_5',['randomUnitVector',['../namespaceICP.html#ac65ba0fbb9f0e58d8217e2500ce141fd',1,'ICP']]],
  ['randomvector3_6',['randomVector3',['../namespaceICP.html#a4712e851c918260483558160a63c5539',1,'ICP']]],
  ['ranges_7',['Typical Plateau Ranges',['../epsilon_sweep_guide.html#esg_typical_ranges',1,'']]],
  ['ray_20projection_20icp_20documentation_8',['Ray-Projection ICP Documentation',['../ray_projection_overview.html',1,'']]],
  ['ray_20projection_20jacobians_9',['Ray-Projection Jacobians',['../ray_projection_overview.html#rpo_jacobians',1,'']]],
  ['ray_20projection_20residual_20jacobians_20on_20se_203_10',['Ray-Projection Residual Jacobians on SE(3)',['../ray_projection_jacobian.html',1,'']]],
  ['ray_20projection_20residual_20with_20incidence_20weighting_20w_20c_11',['Ray-Projection Residual with Incidence Weighting w(c)',['../md_Doc_2JacobianPedantic.html',1,'']]],
  ['raydir_12',['rayDir',['../structICP_1_1OuterParams.html#aa29fc3bc812e57e13f4727d8701a2ee0',1,'ICP::OuterParams']]],
  ['rayhit_13',['RayHit',['../structICP_1_1RayHit.html',1,'ICP']]],
  ['reading_20order_14',['Suggested Reading Order',['../ray_projection_overview.html#rpo_reading',1,'']]],
  ['recipe_15',['Practical Epsilon Sweep Recipe',['../epsilon_sweep_guide.html#esg_practical_recipe',1,'']]],
  ['references_16',['References',['../so3_left_jacobian.html#so3lj_references',1,'']]],
  ['related_20documents_17',['related documents',['../se3_full_chart_jacobian.html#se3_full_related',1,'Related Documents'],['../so3_left_jacobian.html#so3lj_related',1,'Related Documents']]],
  ['remains_201e_206_20for_20simplified_18',['Why Optimal Epsilon Remains 1e-6 for Simplified',['../simplified_jacobian_analysis.html#sja_best_eps',1,'']]],
  ['representation_19',['Advantages of the 7D Ambient Representation',['../se3_ambient_vs_tangent.html#se3_advantages_7d',1,'']]],
  ['residual_20and_20jacobian_20implementation_20',['6. Easier residual and Jacobian implementation',['../se3_ambient_vs_tangent.html#autotoc_md25',1,'']]],
  ['residual_20definition_21',['Residual Definition',['../ray_projection_jacobian.html#rpj_residual',1,'']]],
  ['residual_20jacobians_20on_20se_203_22',['Ray-Projection Residual Jacobians on SE(3)',['../ray_projection_jacobian.html',1,'']]],
  ['residual_20target_20source_20under_20right_20multiplication_23',['6) Backward residual (target -&gt; source) under right-multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md46',1,'']]],
  ['residual_20with_20incidence_20weighting_20w_20c_24',['Ray-Projection Residual with Incidence Weighting w(c)',['../md_Doc_2JacobianPedantic.html',1,'']]],
  ['results_25',['results',['../ray_projection_overview.html#rpo_experimental',1,'Experimental Results'],['../epsilon_sweep_guide.html#esg_plateau_interpretation',1,'Interpreting Results'],['../simplified_jacobian_analysis.html#sja_results',1,'Measured Results']]],
  ['results_20for_20the_20simplified_20jacobian_26',['Interpreting FD Results for the Simplified Jacobian',['../simplified_jacobian_analysis.html',1,'']]],
  ['right_20jacobian_27',['Inverse (Right Jacobian)',['../so3_left_jacobian.html#so3lj_inverse',1,'']]],
  ['right_20jacobian_20test_28',['Right Jacobian Test',['../jacobian_validation.html#jv_right_test',1,'']]],
  ['right_20jacobians_29',['Cross-Validation Between Left and Right Jacobians',['../jacobian_validation.html#jv_cross_validation',1,'']]],
  ['right_20jacobians_20on_20so_203_30',['Validating Left vs Right Jacobians on SO(3)',['../jacobian_validation.html',1,'']]],
  ['right_20multiplication_31',['right multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md46',1,'6) Backward residual (target -&gt; source) under right-multiplication'],['../md_Doc_2JacobianPedantic.html#autotoc_md48',1,'7) Final Jacobian formula to implement (forward, right-multiplication)'],['../md_Doc_2JacobianPedantic.html#autotoc_md31',1,'Correct Jacobians (including dw/dc) for SE(3) right-multiplication']]],
  ['right_20multiplication_20convention_32',['SE(3) Right-Multiplication Convention',['../epsilon_sweep_guide.html#esg_se3_convention',1,'']]],
  ['right_20multiplication_20perturbation_20and_20basic_20jacobians_33',['3) SE(3) right-multiplication perturbation and basic Jacobians',['../md_Doc_2JacobianPedantic.html#autotoc_md37',1,'']]],
  ['right_20multiplicative_34',['SE(3) Full Chart Jacobian (Right-Multiplicative)',['../se3_full_chart_jacobian.html',1,'']]],
  ['right_20multiplicative_20update_20body_20frame_35',['Right-Multiplicative Update (Body Frame)',['../SE3_8h.html#se3_update',1,'']]],
  ['rms_36',['rms',['../structICP_1_1InnerSolveResult.html#a990c7265e484f342a7af195230fe6ec5',1,'ICP::InnerSolveResult']]],
  ['rodrigues_20formula_37',['Using Rodrigues&apos; Formula',['../so3_left_jacobian.html#so3lj_rodrigues',1,'']]],
  ['rotation_38',['rotation',['../so3_left_jacobian.html#so3lj_identity',1,'At Zero Rotation'],['../ray_projection_jacobian.html#rpj_rot_dependence',1,'Both Terms Depend on Rotation'],['../se3_full_chart_jacobian.html#se3_full_dq_dw',1,'Quaternion w.r.t. Rotation']]],
  ['rotation_20away_20from_20delta_200_39',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['rotation_20behave_20differently_40',['Why Translation and Rotation Behave Differently',['../epsilon_sweep_guide.html#esg_linear_vs_nonlinear',1,'']]],
  ['rotation_20components_41',['Rotation Components',['../epsilon_sweep_guide.html#esg_fd_rotation',1,'']]],
  ['rotation_20jacobian_42',['Rotation Jacobian',['../ray_projection_jacobian.html#rpj_rotation',1,'']]],
  ['rotation_3a_20nonlinear_20dependence_43',['Rotation: Nonlinear Dependence',['../epsilon_sweep_guide.html#esg_rotation_nonlinear',1,'']]],
  ['rotation_5fperturbation_44',['ROTATION_PERTURBATION',['../namespaceICP_1_1RandomSeeds.html#a3e9a6f3e14e7c8da0f9fb411d2b96268',1,'ICP::RandomSeeds']]],
  ['rotationpose_45',['rotationPose',['../namespaceICP.html#a192e5beb296e621affbf1d8102377dbf',1,'ICP']]],
  ['rotationthreshold_46',['rotationThreshold',['../structICP_1_1InnerParams.html#a2adf44634936cd1f124021bb8d8a9363',1,'ICP::InnerParams']]],
  ['roundoff_20error_20small_20epsilon_47',['Roundoff Error (Small Epsilon)',['../epsilon_sweep_guide.html#esg_roundoff',1,'']]],
  ['rule_48',['The Quotient Rule',['../ray_projection_jacobian.html#rpj_quotient_rule',1,'']]],
  ['run_20tests_49',['3. Run Tests',['../index.html#autotoc_md5',1,'']]],
  ['runmultiviewicp_50',['runMultiViewICP',['../namespaceICP.html#a452d9634654c28daa44562a06fb656a7',1,'ICP']]]
];
