var searchData=
[
  ['damping_0',['damping',['../structICP_1_1InnerParams.html#a7095e96086d3a7dddab55be7650a0413',1,'ICP::InnerParams']]],
  ['dc_20for_20se_203_20right_20multiplication_1',['Correct Jacobians (including dw/dc) for SE(3) right-multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md31',1,'']]],
  ['dc_20for_20your_20modes_2',['5) Computing w(c) and wp = dw/dc for your modes',['../md_Doc_2JacobianPedantic.html#autotoc_md41',1,'']]],
  ['definition_3',['definition',['../so3_left_jacobian.html#so3lj_definition',1,'Definition'],['../ray_projection_jacobian.html#rpj_residual',1,'Residual Definition']]],
  ['definition_20of_20the_20chart_20jacobian_4',['Definition of the Chart Jacobian',['../se3_full_chart_jacobian.html#se3_full_definition',1,'']]],
  ['definitions_5',['1) Definitions',['../md_Doc_2JacobianPedantic.html#autotoc_md33',1,'']]],
  ['delta_200_6',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['denominator_20dependence_7',['Denominator Dependence',['../ray_projection_jacobian.html#rpj_trans_denominator',1,'']]],
  ['denominator_20derivative_8',['Computing the Denominator Derivative',['../ray_projection_jacobian.html#rpj_rot_db_dw',1,'']]],
  ['denseqr_9',['DenseQR',['../namespaceICP.html#a5f502a0d6b14d9700ebaa884e413b60aa830ab2cb824d151aa1da8b2597bad5f5',1,'ICP']]],
  ['denseschur_10',['DenseSchur',['../namespaceICP.html#a5f502a0d6b14d9700ebaa884e413b60aa556d13290dcf4220b01d05deb79a057c',1,'ICP']]],
  ['depend_20on_20rotation_11',['Both Terms Depend on Rotation',['../ray_projection_jacobian.html#rpj_rot_dependence',1,'']]],
  ['dependence_12',['dependence',['../ray_projection_jacobian.html#rpj_trans_denominator',1,'Denominator Dependence'],['../ray_projection_jacobian.html#rpj_trans_numerator',1,'Numerator Dependence'],['../epsilon_sweep_guide.html#esg_rotation_nonlinear',1,'Rotation: Nonlinear Dependence'],['../epsilon_sweep_guide.html#esg_translation_linear',1,'Translation: Linear Dependence']]],
  ['dependencies_13',['dependencies',['../index.html#autotoc_md3',1,'1. Build Dependencies'],['../index.html#autotoc_md1',1,'Dependencies']]],
  ['depth_5fnoise_14',['DEPTH_NOISE',['../namespaceICP_1_1RandomSeeds.html#a75665791cfe44a0712ffa66f98f595c5',1,'ICP::RandomSeeds']]],
  ['derivation_15',['Derivation',['../so3_left_jacobian.html#so3lj_derivation',1,'']]],
  ['derivative_16',['Computing the Denominator Derivative',['../ray_projection_jacobian.html#rpj_rot_db_dw',1,'']]],
  ['derivative_20of_20r_20w_20c_20a_20c_17',['4) Full derivative of r = w(c) * a/c',['../md_Doc_2JacobianPedantic.html#autotoc_md39',1,'']]],
  ['difference_20behavior_20summary_18',['Finite Difference Behavior Summary',['../ray_projection_jacobian.html#rpj_fd_behavior',1,'']]],
  ['difference_20formulas_19',['Finite-Difference Formulas',['../epsilon_sweep_guide.html#esg_fd_formulas',1,'']]],
  ['difference_20jacobian_20validation_20on_20se_203_20',['Finite-Difference Jacobian Validation on SE(3)',['../epsilon_sweep_guide.html',1,'']]],
  ['difference_20validation_20primary_20test_21',['Finite-Difference Validation (Primary Test)',['../jacobian_validation.html#jv_fd_validation',1,'']]],
  ['differences_22',['differences',['../ray_projection_jacobian.html#rpj_trans_fd',1,'Consequence for Finite Differences'],['../ray_projection_jacobian.html#rpj_validation',1,'Validating Without Finite Differences']]],
  ['differently_23',['Why Translation and Rotation Behave Differently',['../epsilon_sweep_guide.html#esg_linear_vs_nonlinear',1,'']]],
  ['documentation_24',['documentation',['../index.html#autotoc_md11',1,'Documentation'],['../ray_projection_overview.html',1,'Ray-Projection ICP Documentation']]],
  ['documents_25',['documents',['../so3_left_jacobian.html#so3lj_related',1,'Related Documents'],['../se3_full_chart_jacobian.html#se3_full_related',1,'Related Documents']]],
  ['does_20internally_26',['What Ceres Does Internally',['../effective_conditioning.html#cond_ceres_internal',1,'']]],
  ['dr_5fdq_5fmats_27',['dR_dq_mats',['../namespaceICP.html#ab71d2cdd1d648aecf54b730104466eb1',1,'ICP']]],
  ['drtv_5fdq_28',['dRTv_dq',['../namespaceICP.html#a21da7e17faf478c372a7a2e3b7747308',1,'ICP']]],
  ['drv_5fdq_29',['dRv_dq',['../namespaceICP.html#acbec5581196c73bcaa5a52ef768a470a',1,'ICP']]],
  ['dw_20dc_20for_20se_203_20right_20multiplication_30',['Correct Jacobians (including dw/dc) for SE(3) right-multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md31',1,'']]],
  ['dw_20dc_20for_20your_20modes_31',['5) Computing w(c) and wp = dw/dc for your modes',['../md_Doc_2JacobianPedantic.html#autotoc_md41',1,'']]]
];
