var searchData=
[
  ['t_20rotation_0',['Quaternion w.r.t. Rotation',['../se3_full_chart_jacobian.html#se3_full_dq_dw',1,'']]],
  ['t_20rotation_20away_20from_20delta_200_1',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['t_20translation_2',['Translation w.r.t. Translation',['../se3_full_chart_jacobian.html#se3_full_dt_dv',1,'']]],
  ['takeaways_3',['Key Takeaways',['../epsilon_sweep_guide.html#esg_takeaway',1,'']]],
  ['tangent_20formulation_20makes_20sense_4',['When a Pure 6D Tangent Formulation Makes Sense',['../se3_ambient_vs_tangent.html#se3_when_tangent',1,'']]],
  ['tangent_20parameterization_5',['SE(3) Optimization: 7D Ambient vs 6D Tangent Parameterization',['../se3_ambient_vs_tangent.html',1,'']]],
  ['tangent6_6',['Tangent6',['../namespaceICP.html#a16b7297a68b502b0141c5e7798bfa65e',1,'ICP']]],
  ['target_7',['Forward Case (Source to Target)',['../ray_projection_jacobian.html#rpj_forward',1,'']]],
  ['target_20source_20under_20right_20multiplication_8',['6) Backward residual (target -&gt; source) under right-multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md46',1,'']]],
  ['target_20to_20source_9',['Backward Case (Target to Source)',['../ray_projection_jacobian.html#rpj_backward',1,'']]],
  ['tau_10',['tau',['../md_Doc_2JacobianPedantic.html#autotoc_md42',1,'Case A: enable_gate and abs(c) &lt; tau'],['../structICP_1_1GeometryWeighting.html#acd0f0ae794b142eabe465b061a38db5a',1,'ICP::GeometryWeighting::tau']]],
  ['term_11',['The Missing Term',['../ray_projection_jacobian.html#rpj_rot_missing',1,'']]],
  ['terms_20depend_20on_20rotation_12',['Both Terms Depend on Rotation',['../ray_projection_jacobian.html#rpj_rot_dependence',1,'']]],
  ['test_13',['test',['../jacobian_validation.html#jv_fd_validation',1,'Finite-Difference Validation (Primary Test)'],['../jacobian_validation.html#jv_left_test',1,'Left Jacobian Test'],['../jacobian_validation.html#jv_right_test',1,'Right Jacobian Test']]],
  ['test_20function_14',['Simple Sanity Test Function',['../jacobian_validation.html#jv_sanity_test',1,'']]],
  ['tests_15',['3. Run Tests',['../index.html#autotoc_md5',1,'']]],
  ['that_20are_20always_20zero_16',['Blocks That Are Always Zero',['../se3_full_chart_jacobian.html#se3_full_zero_blocks',1,'']]],
  ['the_207d_20ambient_20representation_17',['Advantages of the 7D Ambient Representation',['../se3_ambient_vs_tangent.html#se3_advantages_7d',1,'']]],
  ['the_20chart_20jacobian_18',['Definition of the Chart Jacobian',['../se3_full_chart_jacobian.html#se3_full_definition',1,'']]],
  ['the_20consistent_20jacobian_20matches_20fd_19',['Why the Consistent Jacobian Matches FD',['../simplified_jacobian_analysis.html#sja_consistent_validated',1,'']]],
  ['the_20critical_20translation_20pitfall_20',['The Critical Translation Pitfall',['../epsilon_sweep_guide.html#esg_critical_pitfall',1,'']]],
  ['the_20denominator_20derivative_21',['Computing the Denominator Derivative',['../ray_projection_jacobian.html#rpj_rot_db_dw',1,'']]],
  ['the_20key_20rule_22',['The Key Rule',['../effective_conditioning.html#cond_key_rule',1,'']]],
  ['the_20matrix_20exponential_23',['From the Matrix Exponential',['../so3_left_jacobian.html#so3lj_series',1,'']]],
  ['the_20missing_20term_24',['The Missing Term',['../ray_projection_jacobian.html#rpj_rot_missing',1,'']]],
  ['the_20plateau_20phenomenon_25',['The Plateau Phenomenon',['../epsilon_sweep_guide.html#esg_plateau',1,'']]],
  ['the_20quotient_20rule_26',['The Quotient Rule',['../ray_projection_jacobian.html#rpj_quotient_rule',1,'']]],
  ['the_20simplified_20error_20is_20around_200_20005_20to_200_2001_27',['Why the Simplified Error is Around 0.005 to 0.01',['../simplified_jacobian_analysis.html#sja_error_magnitude',1,'']]],
  ['the_20simplified_20jacobian_28',['Interpreting FD Results for the Simplified Jacobian',['../simplified_jacobian_analysis.html',1,'']]],
  ['the_20simplified_20jacobian_20is_20missing_29',['What the Simplified Jacobian is Missing',['../simplified_jacobian_analysis.html#sja_missing_term',1,'']]],
  ['theory_30',['7. Conceptual alignment with Lie theory',['../se3_ambient_vs_tangent.html#autotoc_md27',1,'']]],
  ['to_200_2001_31',['Why the Simplified Error is Around 0.005 to 0.01',['../simplified_jacobian_analysis.html#sja_error_magnitude',1,'']]],
  ['to_20implement_20forward_20right_20multiplication_32',['7) Final Jacobian formula to implement (forward, right-multiplication)',['../md_Doc_2JacobianPedantic.html#autotoc_md48',1,'']]],
  ['to_20source_33',['Backward Case (Target to Source)',['../ray_projection_jacobian.html#rpj_backward',1,'']]],
  ['to_20target_34',['Forward Case (Source to Target)',['../ray_projection_jacobian.html#rpj_forward',1,'']]],
  ['toceressolveroptions_35',['toCeresSolverOptions',['../namespaceICP.html#a3cbd81b918a87781d449fb5ae842256d',1,'ICP']]],
  ['translation_36',['Concrete Example: Scaling Rotation vs Translation',['../effective_conditioning.html#cond_example',1,'']]],
  ['translation_20and_20rotation_20behave_20differently_37',['Why Translation and Rotation Behave Differently',['../epsilon_sweep_guide.html#esg_linear_vs_nonlinear',1,'']]],
  ['translation_20components_38',['Translation Components',['../epsilon_sweep_guide.html#esg_fd_translation',1,'']]],
  ['translation_20jacobian_39',['Translation Jacobian',['../ray_projection_jacobian.html#rpj_translation',1,'']]],
  ['translation_20jacobian_20both_20consistent_20and_20simplified_40',['Translation Jacobian (Both Consistent and Simplified)',['../ray_projection_jacobian.html#rpj_trans_jacobian',1,'']]],
  ['translation_20pitfall_41',['The Critical Translation Pitfall',['../epsilon_sweep_guide.html#esg_critical_pitfall',1,'']]],
  ['translation_20w_20r_20t_20rotation_20away_20from_20delta_200_42',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['translation_20w_20r_20t_20translation_43',['Translation w.r.t. Translation',['../se3_full_chart_jacobian.html#se3_full_dt_dv',1,'']]],
  ['translation_3a_20linear_20dependence_44',['Translation: Linear Dependence',['../epsilon_sweep_guide.html#esg_translation_linear',1,'']]],
  ['translation_5fperturbation_45',['TRANSLATION_PERTURBATION',['../namespaceICP_1_1RandomSeeds.html#a099c676d4e48f1c22bc81b2d2246ab61',1,'ICP::RandomSeeds']]],
  ['translationpose_46',['translationPose',['../namespaceICP.html#acff0db22f66f05ec28d2ad13c473f1a7',1,'ICP']]],
  ['translationthreshold_47',['translationThreshold',['../structICP_1_1InnerParams.html#a260edbec709bb9591b2e19465b17e41c',1,'ICP::InnerParams']]],
  ['triangulation_48',['Grid Triangulation',['../TriangulationMarks_8h.html#triangulation_grid',1,'']]],
  ['triangulationmarks_2eh_49',['TriangulationMarks.h',['../TriangulationMarks_8h.html',1,'']]],
  ['trigonometry_20free_20state_20storage_50',['1. Trigonometry-free state storage',['../se3_ambient_vs_tangent.html#autotoc_md15',1,'']]],
  ['truncation_20error_20large_20epsilon_51',['Truncation Error (Large Epsilon)',['../epsilon_sweep_guide.html#esg_truncation',1,'']]],
  ['two_20competing_20errors_52',['Two Competing Errors',['../epsilon_sweep_guide.html#esg_competing_errors',1,'']]],
  ['typical_20plateau_20ranges_53',['Typical Plateau Ranges',['../epsilon_sweep_guide.html#esg_typical_ranges',1,'']]]
];
