var searchData=
[
  ['easier_20residual_20and_20jacobian_20implementation_0',['6. Easier residual and Jacobian implementation',['../se3_ambient_vs_tangent.html#autotoc_md25',1,'']]],
  ['edge_1',['Edge',['../structICP_1_1Edge.html',1,'ICP']]],
  ['effective_20conditioning_20via_20manifold_20scaling_2',['Effective Conditioning via Manifold Scaling',['../effective_conditioning.html',1,'']]],
  ['eigentypes_2eh_3',['EigenTypes.h',['../EigenTypes_8h.html',1,'']]],
  ['eigenutils_2eh_4',['EigenUtils.h',['../EigenUtils_8h.html',1,'']]],
  ['embree_5',['Embree',['../namespaceICP.html#ac9175383bab1fe0ac0b38352692cd240a4a8800d06957e26c4e0f41db48342ed2',1,'ICP']]],
  ['embreebackend_6',['EmbreeBackend',['../classICP_1_1EmbreeBackend.html',1,'ICP']]],
  ['enable_5fgate_7',['enable_gate',['../structICP_1_1GeometryWeighting.html#ac5de31e53c339e5d2d7255cfaddf90a8',1,'ICP::GeometryWeighting']]],
  ['enable_5fgate_20and_20abs_20c_20tau_8',['Case A: enable_gate and abs(c) &lt; tau',['../md_Doc_2JacobianPedantic.html#autotoc_md42',1,'']]],
  ['enable_5fweight_9',['enable_weight',['../md_Doc_2JacobianPedantic.html#autotoc_md43',1,'Case B: not enable_weight'],['../structICP_1_1GeometryWeighting.html#a69be7f5e37b74bc2d882f1e565ee7e48',1,'ICP::GeometryWeighting::enable_weight']]],
  ['enable_5fweight_20and_20not_20gated_10',['Case C: enable_weight and not gated',['../md_Doc_2JacobianPedantic.html#autotoc_md44',1,'']]],
  ['enabled_11',['enabled',['../structICP_1_1LineSearchParams.html#a0cc8cb3733a39a7657cdfb7758e206c4',1,'ICP::LineSearchParams']]],
  ['encoding_12',['Facet ID Encoding',['../TriangulationMarks_8h.html#triangulation_facet',1,'']]],
  ['epsilon_13',['epsilon',['../epsilon_sweep_guide.html#esg_roundoff',1,'Roundoff Error (Small Epsilon)'],['../epsilon_sweep_guide.html#esg_truncation',1,'Truncation Error (Large Epsilon)']]],
  ['epsilon_20remains_201e_206_20for_20simplified_14',['Why Optimal Epsilon Remains 1e-6 for Simplified',['../simplified_jacobian_analysis.html#sja_best_eps',1,'']]],
  ['epsilon_20sweep_20recipe_15',['Practical Epsilon Sweep Recipe',['../epsilon_sweep_guide.html#esg_practical_recipe',1,'']]],
  ['error_20is_20around_200_20005_20to_200_2001_16',['Why the Simplified Error is Around 0.005 to 0.01',['../simplified_jacobian_analysis.html#sja_error_magnitude',1,'']]],
  ['error_20large_20epsilon_17',['Truncation Error (Large Epsilon)',['../epsilon_sweep_guide.html#esg_truncation',1,'']]],
  ['error_20small_20epsilon_18',['Roundoff Error (Small Epsilon)',['../epsilon_sweep_guide.html#esg_roundoff',1,'']]],
  ['errors_19',['Two Competing Errors',['../epsilon_sweep_guide.html#esg_competing_errors',1,'']]],
  ['euclidean_20group_20',['SE(3): Special Euclidean Group',['../SE3_8h.html#se3_se3',1,'']]],
  ['evaluate_21',['evaluate',['../classICP_1_1ReverseRayLeft_3_01RayJacobianSimplified_01_4.html#a746b6ce1e90d26131cd6bb7bfafcaf75',1,'ICP::ReverseRayLeft&lt; RayJacobianSimplified &gt;::Evaluate()'],['../classICP_1_1ForwardRayLeft_3_01RayJacobianSimplified_01_4.html#a07c753b3e23ebc32af3c6db1adf4cd2c',1,'ICP::ForwardRayLeft&lt; RayJacobianSimplified &gt;::Evaluate()']]],
  ['example_3a_20scaling_20rotation_20vs_20translation_22',['Concrete Example: Scaling Rotation vs Translation',['../effective_conditioning.html#cond_example',1,'']]],
  ['experimental_20results_23',['Experimental Results',['../ray_projection_overview.html#rpo_experimental',1,'']]],
  ['exponential_24',['From the Matrix Exponential',['../so3_left_jacobian.html#so3lj_series',1,'']]],
  ['exponential_20map_25',['Context: SE(3) Exponential Map',['../so3_left_jacobian.html#so3lj_context',1,'']]],
  ['exponential_20map_20quaternion_20form_26',['SO(3) Exponential Map (Quaternion Form)',['../SE3_8h.html#se3_expso3',1,'']]],
  ['expression_27',['Closed-Form Expression',['../so3_left_jacobian.html#so3lj_closed_form',1,'']]]
];
