var searchData=
[
  ['facet_20id_20encoding_0',['Facet ID Encoding',['../TriangulationMarks_8h.html#triangulation_facet',1,'']]],
  ['facetconfigll_1',['FacetConfigLL',['../TriangulationMarks_8h.html#a1db2083c421e2e1d465170d0bef37094',1,'TriangulationMarks']]],
  ['facetconfiglr_2',['FacetConfigLR',['../TriangulationMarks_8h.html#aa06f1235364dd852c092220e139eac91',1,'TriangulationMarks']]],
  ['facetconfigmask_3',['FacetConfigMask',['../TriangulationMarks_8h.html#a3e18c52cc4e10ec92468e69f359b3ec7',1,'TriangulationMarks']]],
  ['facetconfigul_4',['FacetConfigUL',['../TriangulationMarks_8h.html#a54960e7fc31b6c1f46c7bf7118c84bc6',1,'TriangulationMarks']]],
  ['facetconfigur_5',['FacetConfigUR',['../TriangulationMarks_8h.html#aa68d1c7fcebecead3dc4dcb60e91ab2d',1,'TriangulationMarks']]],
  ['fails_6',['When Simplified Fails',['../ray_projection_jacobian.html#rpj_when_simplified',1,'']]],
  ['fd_7',['Why the Consistent Jacobian Matches FD',['../simplified_jacobian_analysis.html#sja_consistent_validated',1,'']]],
  ['fd_20results_20for_20the_20simplified_20jacobian_8',['Interpreting FD Results for the Simplified Jacobian',['../simplified_jacobian_analysis.html',1,'']]],
  ['final_20forms_9',['Final Forms',['../se3_full_chart_jacobian.html#se3_full_final_form',1,'']]],
  ['final_20jacobian_20formula_20to_20implement_20forward_20right_20multiplication_10',['7) Final Jacobian formula to implement (forward, right-multiplication)',['../md_Doc_2JacobianPedantic.html#autotoc_md48',1,'']]],
  ['finite_20difference_20behavior_20summary_11',['Finite Difference Behavior Summary',['../ray_projection_jacobian.html#rpj_fd_behavior',1,'']]],
  ['finite_20difference_20formulas_12',['Finite-Difference Formulas',['../epsilon_sweep_guide.html#esg_fd_formulas',1,'']]],
  ['finite_20difference_20jacobian_20validation_20on_20se_203_13',['Finite-Difference Jacobian Validation on SE(3)',['../epsilon_sweep_guide.html',1,'']]],
  ['finite_20difference_20validation_20primary_20test_14',['Finite-Difference Validation (Primary Test)',['../jacobian_validation.html#jv_fd_validation',1,'']]],
  ['finite_20differences_15',['finite differences',['../ray_projection_jacobian.html#rpj_trans_fd',1,'Consequence for Finite Differences'],['../ray_projection_jacobian.html#rpj_validation',1,'Validating Without Finite Differences']]],
  ['fixedlambda_16',['fixedLambda',['../structICP_1_1LMParams.html#a06abb42b6bac12e5329a562a1095ddcc',1,'ICP::LMParams']]],
  ['fixfirstpose_17',['fixFirstPose',['../structICP_1_1SessionParams.html#aa91045ad5486f90bf7daec59280ec4fe',1,'ICP::SessionParams']]],
  ['for_20finite_20differences_18',['Consequence for Finite Differences',['../ray_projection_jacobian.html#rpj_trans_fd',1,'']]],
  ['for_20pulling_20back_20ambient_20jacobians_19',['Chart Jacobian for Pulling Back Ambient Jacobians',['../SE3_8h.html#se3_chart_jac',1,'']]],
  ['for_20se_203_20right_20multiplication_20',['Correct Jacobians (including dw/dc) for SE(3) right-multiplication',['../md_Doc_2JacobianPedantic.html#autotoc_md31',1,'']]],
  ['for_20simplified_21',['Why Optimal Epsilon Remains 1e-6 for Simplified',['../simplified_jacobian_analysis.html#sja_best_eps',1,'']]],
  ['for_20the_20simplified_20jacobian_22',['Interpreting FD Results for the Simplified Jacobian',['../simplified_jacobian_analysis.html',1,'']]],
  ['for_20your_20modes_23',['5) Computing w(c) and wp = dw/dc for your modes',['../md_Doc_2JacobianPedantic.html#autotoc_md41',1,'']]],
  ['form_24',['SO(3) Exponential Map (Quaternion Form)',['../SE3_8h.html#se3_expso3',1,'']]],
  ['form_20expression_25',['Closed-Form Expression',['../so3_left_jacobian.html#so3lj_closed_form',1,'']]],
  ['forms_26',['Final Forms',['../se3_full_chart_jacobian.html#se3_full_final_form',1,'']]],
  ['formula_27',['Using Rodrigues&apos; Formula',['../so3_left_jacobian.html#so3lj_rodrigues',1,'']]],
  ['formula_20to_20implement_20forward_20right_20multiplication_28',['7) Final Jacobian formula to implement (forward, right-multiplication)',['../md_Doc_2JacobianPedantic.html#autotoc_md48',1,'']]],
  ['formulas_29',['Finite-Difference Formulas',['../epsilon_sweep_guide.html#esg_fd_formulas',1,'']]],
  ['formulation_20makes_20sense_30',['When a Pure 6D Tangent Formulation Makes Sense',['../se3_ambient_vs_tangent.html#se3_when_tangent',1,'']]],
  ['forward_20case_20source_20to_20target_31',['Forward Case (Source to Target)',['../ray_projection_jacobian.html#rpj_forward',1,'']]],
  ['forward_20right_20multiplication_32',['7) Final Jacobian formula to implement (forward, right-multiplication)',['../md_Doc_2JacobianPedantic.html#autotoc_md48',1,'']]],
  ['forwardrayleft_3c_20rayjacobiansimplified_20_3e_33',['ForwardRayLeft&lt; RayJacobianSimplified &gt;',['../classICP_1_1ForwardRayLeft_3_01RayJacobianSimplified_01_4.html',1,'ICP']]],
  ['foundations_34',['Mathematical Foundations',['../ray_projection_overview.html#rpo_foundations',1,'']]],
  ['frame_35',['Right-Multiplicative Update (Body Frame)',['../SE3_8h.html#se3_update',1,'']]],
  ['free_20state_20storage_36',['1. Trigonometry-free state storage',['../se3_ambient_vs_tangent.html#autotoc_md15',1,'']]],
  ['freedom_20is_20harmless_37',['5. Quaternion gauge freedom is harmless',['../se3_ambient_vs_tangent.html#autotoc_md23',1,'']]],
  ['from_20delta_200_38',['Translation w.r.t. Rotation (Away from delta = 0)',['../se3_full_chart_jacobian.html#se3_full_dt_dw',1,'']]],
  ['from_20the_20matrix_20exponential_39',['From the Matrix Exponential',['../so3_left_jacobian.html#so3lj_series',1,'']]],
  ['full_20chart_20jacobian_20right_20multiplicative_40',['SE(3) Full Chart Jacobian (Right-Multiplicative)',['../se3_full_chart_jacobian.html',1,'']]],
  ['full_20derivative_20of_20r_20w_20c_20a_20c_41',['4) Full derivative of r = w(c) * a/c',['../md_Doc_2JacobianPedantic.html#autotoc_md39',1,'']]],
  ['function_42',['Simple Sanity Test Function',['../jacobian_validation.html#jv_sanity_test',1,'']]],
  ['functions_43',['Cost Functions',['../ICPCeresSolver_8h.html#icpceres_costs',1,'']]]
];
